//////////////////////////////////////////////////////////////////////
// Object2VR pro 4.0beta2/20670 Object Player                       //
// Trial License: For evaluation only!                              //
// (c) 2023, Garden Gnome Software, https://ggnome.com              //
//////////////////////////////////////////////////////////////////////

var __extends=this&&this.__extends||function(){function y(B,A){y=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,a){h.__proto__=a}||function(h,a){for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&(h[b]=a[b])};return y(B,A)}return function(B,A){function h(){this.constructor=B}if("function"!==typeof A&&null!==A)throw new TypeError("Class extends value "+String(A)+" is not a constructor or null");y(B,A);B.prototype=null===A?Object.create(A):(h.prototype=A.prototype,new h)}}(),
g;
(function(y){var B=function(){function h(){this.s=this.value=0;this.Sb=-1;this.unit="px"}h.prototype.qc=function(a,b,c){if(a.hasOwnProperty("value")){var d=a.value;a.hasOwnProperty("unit")||(a.unit="px");if("px"==a.unit||"%"==a.unit)this.unit!=a.unit&&(this.value="%"==a.unit?this.value/c*100:this.value*c/100),this.unit=a.unit}b&&b.hasOwnProperty("duration")&&0<b.duration||(this.value=d);this.Sb=d};h.prototype.qb=function(a,b){void 0===b&&(b=-1);-1==b&&(b=this.value);this.s="%"==this.unit?.01*b*a:
b};h.prototype.Xb=function(a,b){-1!=this.Sb&&(this.Sb==this.value?this.qb(b):(this.qb(b,this.value+(this.Sb-this.value)*a),1<=a&&(this.value=this.Sb)))};return h}();y.Tb=B;y.ri=function(){return function(){this.X=this.J=this.pan=0}}();var A=function(){return function(){this.Zd=-1E7;this.Lg=!1}}();y.pi=A;B=function(){function h(){this.Ld="aHR0cHM6Ly9nZ25vbWUuY29t";this.Md="Q3JlYXRlZCBieSBHbm9tZXM=";this.Le="VHJpYWwgTGljZW5zZTogRm9yIGV2YWx1YXRpb24gb25seSE=";this.xf=!0;this.P={width:10,height:10};this.crossOrigin="anonymous";this.Od=1;this.O=
{};this.Jb=this.vb="";this.Ve=[];this.Ie=!1;this.fc=0;this.control=this.N=this.W=this.m=this.T=null;this.La=[];this.v=this.oa=!1;this.u=null;this.bc=!1;this.oc=0;this.aa=null;this.ra={};this.sb={};this.Z={};this.K={};this.D={mode:1,Je:-1,M:0,V:0,ta:.05,Ja:255,Ta:1,ja:255,Sa:.3,ac:!0,td:{enabled:!0,width:180,height:20,ud:0,nf:1,background:!0,ja:16777215,Sa:1,Ja:0,Ta:1,zc:3,Ac:1,Dd:!0},$:[],fa:[],qa:[],uc:[]};this.fb=null;this.G=[];this.Qh=-1;this.R=null;this.wb={};this.ga={};this.mf=this.pb="";this.lf=
-1;this.margin={left:new y.Tb,top:new y.Tb,right:new y.Tb,bottom:new y.Tb,transition:{}};this.lc=[];this.I={x:0,y:0};this.Kg=!1;this.Ia="";this.Uf="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAA5JREFUeNpiYBgeACDAAADIAAE3iTbkAAAAAElFTkSuQmCC";this.ka="";this.$c=this.dd=this.Ee=this.Zc=this.bd=this.ad=this.ed=this.ec=this.hb=this.Ce=this.Be=this.De=this.Fe=this.cd=this.He=!1;this.devicePixelRatio=1;this.Ne="<<LOG>>";this.zd=!1;
this.qg=function(a){return a?this.gb()&&(a.clientX||a.clientY)?{x:a.clientX,y:a.clientY}:a.pageX||a.pageY?{x:a.pageX,y:a.pageY}:a.clientX||a.clientY?{x:a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,y:a.clientY+document.body.scrollTop+document.documentElement.scrollTop}:a.touches&&a.touches[0]?{x:a.touches[0].pageX,y:a.touches[0].pageY}:{x:0,y:0}:{x:0,y:0}};this.rg=function(a){a=this.qg(a);var b=this.Fa();return{x:a.x-b.x,y:a.y-b.y}};this.Kh=function(a,b,c){var d=this;var f=
"<<U>>"+String(d.ka);f=f.toUpperCase();"U"!=f.charAt(2)&&(d.i.cc=!1);if(d.ua)d.m.removeChild(d.ua),d.ua=null;else{d.ua=document.createElement("div");var l=d.ua;f="left: "+a+"px;top:\t "+(b+"px;z-index: 32000;");f+="position:relative;";f+="display: table;";f+="color: black;";f+="background-color: white;";f+="border: 1px solid lightgray;";f+="box-shadow: 1px 1px 3px #333;";f+="font-family: Verdana, Arial, Helvetica, sans-serif;";f+="font-size: 9pt;";f+="opacity : 0.95;";l.setAttribute("style",f);l.setAttribute("class",
"gg_contextmenu");f=document.createElement("style");a=document.createTextNode(".gg_context_row:hover { background-color: #3399FF }");f.type="text/css";f.styleSheet?f.styleSheet.cssText=a.nodeValue:f.appendChild(a);l.appendChild(f);for(a=0;a<d.lc.length;a++)if(b=d.lc[a],""!=b.text){var k=document.createElement("div");f="text-align: left;";f+="margin: 0;";f+="padding: 5px 20px;";f+="vertical-align: left;";k.setAttribute("style",f);k.setAttribute("class","gg_context_row");""!=b.url?(f=document.createElement("a"),
f.href=b.url,f.target="_blank",f.innerHTML=this.Ra(b.text),f.setAttribute("style","color: black; text-decoration: none;"),k.appendChild(f)):(f=document.createElement("span"),f.innerHTML=this.Ra(b.text),f.setAttribute("style","color: black; text-decoration: none;"),k.appendChild(f));l.appendChild(k)}0<d.lc.length&&(0<c.length||!d.i.cc)&&l.appendChild(document.createElement("hr"));for(f=0;f<c.length;f++)a=c[f],a.hasOwnProperty("hr")?l.appendChild(document.createElement("hr")):(b=document.createElement("div"),
b.setAttribute("class","gg_context_row"),a.hasOwnProperty("style")&&b.setAttribute("style",a.style),a.hasOwnProperty("onclick")&&(b.onclick=a.onclick),b.innerHTML=a.innerHTML,l.appendChild(b));d.i.cc||(c=document.createElement("div"),f="text-align: left;margin: 0;padding: 5px 20px;",f+="vertical-align: left;",c.setAttribute("style",f),c.setAttribute("class","gg_context_row"),f=document.createElement("a"),f.href=h.Nc(d.Ld),f.target="_blank",f.innerHTML=h.Nc(d.Md),7<this.Ne.length&&(f.innerHTML+="<br/>"+
h.Sf(d.Ne).replace(/./gm,function(n){return"&#"+n.charCodeAt(0)+";"})),f.setAttribute("style","color: black; text-decoration: none;"),c.appendChild(f),l.appendChild(c));d.m.insertBefore(d.ua,d.m.firstChild);l.onclick=function(){d.ua&&(d.m.removeChild(d.ua),d.ua=null)};l.oncontextmenu=l.onclick}};this.Lb="";this.be();this.checkLoaded=this.La;this.isLoaded=!1}h.prototype.Wc=function(a){return-99991===a?this.Le:"4.0beta2/20670"};h.prototype.Zf=function(){return this.Od};h.prototype.lh=function(a){0<
a&&(this.Od=a)};h.prototype.Nd=function(a){if(""!=a)try{var b=void 0;b="object"===typeof a?a:JSON.parse(a);if("object"===typeof b)for(var c in b)if("translations"==c&&this.O.hasOwnProperty("translations")){var d=b[c],f;for(f in d)if(this.O.translations.hasOwnProperty(f))for(a=0;a<d[f].length-1;a++)""!=d[f][a]&&(this.O.translations[f][a]=d[f][a]);else this.O.translations[f]=d[f]}else this.O[c]=b[c];this.O.hasOwnProperty("projectLanguage")&&(this.Jb=this.O.projectLanguage);this.o("languagechanged",
{language:this.vb})}catch(l){console.error(l)}};h.prototype.Ra=function(a,b){var c=a;if(""!=c&&"object"===typeof this.O&&this.O.hasOwnProperty("languages")&&this.O.hasOwnProperty("translations")){var d=this.O.languages.indexOf(this.vb);-1!=d&&this.O.translations.hasOwnProperty(a)&&(a=this.O.translations[a],Array.isArray(a)&&a.length>d&&""!=a[d]&&(c=a[d]))}if(b&&0<b.length)for(d=b.length-1;0<=d;d--)c=c.replace(new RegExp("%"+String(d+1),"g"),b[d]);return c};h.prototype.$e=function(a){this.Ie=!0;a=
a.replace("_","-");if("object"===typeof this.O&&this.O.hasOwnProperty("languages")&&this.O.hasOwnProperty("translations")&&this.Jb!=a){for(var b=-1,c=-1,d="",f=-1,l=-1,k=a.substring(0,2).toUpperCase(),n=0;n<this.O.languages.length;n++)if(this.O.languages[n].toUpperCase()==a.toUpperCase()){b=n;break}else if(!this.Jb.toUpperCase().startsWith(k)&&this.O.languages[n].toUpperCase().startsWith(k)){if(""==d||-1!=d.indexOf("-"))c=n,d=this.O.languages[n]}else for(var m=window.navigator.languages,e=0;e<m.length;e++)!this.Jb.toUpperCase().startsWith(k)&&
this.O.languages[n].toUpperCase().startsWith(m[e].substring(0,2).toUpperCase())&&(-1==l||e<l)&&(f=n,l=e);a=-1!=b?b:-1!=c?c:f;a=-1!=a?this.O.languages[a]:this.Jb}this.vb!=a&&(this.vb=a,this.m.setAttribute("lang",a),this.o("languagechanged",{language:a}))};h.prototype.lg=function(){return this.vb};h.prototype.Ag=function(){return this.Ve};h.prototype.addListener=function(a,b){(this.wb[a]=this.wb[a]||[]).push(b)};h.prototype.o=function(a,b){if(a=this.wb[a])for(var c=a.length,d=0;d<c;d++)try{a[d].apply(null,
[b])}catch(f){this.Me(f)}};h.prototype.removeEventListener=function(a,b){var c=this.wb[a];if(c){var d;var f=0;for(d=c.length;f<d;f++)if(c[f]===b){1===d?delete this.wb[a]:c.splice(f,1);break}}};h.prototype.ih=function(){this.v=!0};h.prototype.Gf=function(a,b,c,d){if(!this.ga.hasOwnProperty(a)){var f=new A;this.ga[a]=f;f.type=b;"undefined"!==typeof c&&this.sc(a,c);"object"===typeof d&&this.ef(a,d);return!0}return!1};h.je=function(a){var b=document.cookie.indexOf(a+"="),c="";-1!=b&&(b=b+a.length+1,a=
document.cookie.indexOf(";",b),-1==a&&(a=document.cookie.length),c=decodeURIComponent(document.cookie.substring(b,a)));return c};h.Eh=function(a,b){0==a.type?a.value="string"===typeof b?b:b.toString():1==a.type?a.value="string"===typeof b?parseFloat(b):"number"===typeof b?b:b?1:0:2==a.type&&(a.value="string"===typeof b?"false"!==b&&""!==b&&"0"!==b:"number"===typeof b?0!=b:!!b)};h.prototype.ef=function(a,b){if(this.ga.hasOwnProperty(a)&&"object"===typeof b){var c=this.ga[a];b.hasOwnProperty("cookiePath")&&
(c.$d=String(b.cookiePath));b.hasOwnProperty("cookieExpireDays")&&(c.Zd=parseFloat(b.cookieExpireDays));if(b.hasOwnProperty("keep")&&(c.fd=!!b.keep,c.fd&&0<document.cookie.length))if(""!=this.pb){if(-1!=document.cookie.indexOf(this.pb+"=")){var d=JSON.parse(h.je(this.pb));d.hasOwnProperty(a)&&this.sc(a,d[a])}}else d="ggvar_"+a,-1!=document.cookie.indexOf(d+"=")&&(d=h.je(d),this.sc(a,d));b.hasOwnProperty("ignoreInState")&&(c.Lg=b.ignoreInState);b.hasOwnProperty("customProperty")&&"object"===typeof b.customProperty&&
(b=b.customProperty,this.K.hasOwnProperty(a)?(this.K[a].variabletype!=b.variableType||this.K[a].propertytype!=b.propertyType)&&console.log("Custom property added as variable has different types than custom property from project."):this.K[a]={xa:b.variableType,Kb:b.propertyType,Pc:b.defaultValue});return!0}return!1};h.prototype.Dh=function(a,b){this.pb=a;b&&"object"===typeof b&&(b.hasOwnProperty("cookiePath")&&(this.mf=String(b.cookiePath)),b.hasOwnProperty("cookieExpireDays")&&(this.lf=parseFloat(b.cookieExpireDays)))};
h.Pd=function(a,b,c){-1<=b&&(a+="; max-age="+86400*b);""!=c&&(a+="; path="+c);return a};h.ke=function(a,b){switch(b){case 0:return a;case 1:return a.toString();case 2:return a?"true":"false"}};h.Uc=function(a,b){switch(b){case 0:return a;case 1:return Number(a);case 2:return"true"==a}};h.prototype.Dg=function(a,b){""==a&&(a="node1");return this.sb.hasOwnProperty(a)&&this.sb[a].hasOwnProperty(b)?this.$b(y.yc.Uc(this.sb[a][b],this.K[b].xa),this.K[b].xa):null};h.prototype.Ch=function(a,b,c){c="string"===
typeof c?c:y.yc.ke(c,this.K[b].xa);this.sb[a][b]!=c&&(this.sb[a][b]=c,this.o("varchanged_"+b,{}))};h.prototype.ne=function(a,b,c){""==a&&(a="node1");return this.Z.hasOwnProperty(a)&&this.Z[a].hasOwnProperty(b)&&this.Z[a][b].hasOwnProperty(c)?this.$b(h.Uc(this.Z[a][b][c],this.K[c].xa),this.K[c].xa):this.K.hasOwnProperty(c)?this.$b(h.Uc(this.K[c].Pc,this.K[c].xa),this.K[c].xa):null};h.prototype.Ze=function(a,b,c,d){""==a&&(a="node1");d="string"===typeof d?d:h.ke(d,this.K[c].xa);this.Z.hasOwnProperty(a)||
(this.Z[a]={});this.Z[a].hasOwnProperty(b)||(this.Z[a][b]={});this.Z[a][b].hasOwnProperty(c)&&this.Z[a][b][c]==d||(this.Z[a][b][c]=d,this.o("varchanged_"+c,{}))};h.prototype.cg=function(a){return this.K.hasOwnProperty(a)?this.K[a].Pc:null};h.prototype.yb=function(){return"object"};h.prototype.sc=function(a,b,c){void 0===c&&(c=!0);if(void 0===b)return!1;var d=!1;this.K.hasOwnProperty(a)&&(0==this.K[a].Kb?(this.Ch(this.yb(),a,b),d=!0):1==this.K[a].Kb&&this.C&&(this.Ze(this.yb(),this.C.id,a,b),d=!0));
if(this.ga.hasOwnProperty(a)){var f=this.ga[a];if(f.value!=b){h.Eh(f,b);if(f.fd&&c){if(""!=this.pb){f={};for(var l=0,k=Object.keys(this.ga);l<k.length;l++)c=k[l],this.ga[c].fd&&(f[c]=encodeURIComponent(this.ga[c].value.toString()));c=this.pb+"="+JSON.stringify(f);c=h.Pd(c,this.lf,this.mf)}else c="ggvar_"+a+"="+encodeURIComponent(b.toString()),c=h.Pd(c,f.Zd,f.$d?f.$d:"");document.cookie=c}d||this.o("varchanged_"+a,{value:b})}return!0}return!1};h.prototype.$b=function(a,b){return 0==b?this.Ra(a):a};
h.prototype.Gg=function(a,b){void 0===b&&(b="");if(this.K.hasOwnProperty(a)){if(0==this.K[a].Kb)return this.Dg(this.yb(),a);if(1==this.K[a].Kb){if(""!=b||this.C&&this.C!=this.ma)return this.ne(this.yb(),""!=b?b:this.C.id,a);switch(this.K[a].xa){case 0:return"";case 1:return 0;case 2:return!1}}}if(this.ga.hasOwnProperty(a))return this.$b(this.ga[a].value,this.ga[a].type)};h.Nc=function(a){var b="",c=0;a=a.replace(/[^A-Za-z0-9+\/=]/g,"");do{var d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(c++));
var f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(c++));var l="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(c++));var k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(c++));d=d<<2|f>>4;f=(f&15)<<4|l>>2;var n=(l&3)<<6|k;b+=String.fromCharCode(d);64!=l&&(b+=String.fromCharCode(f));64!=k&&(b+=String.fromCharCode(n))}while(c<a.length);return b};h.Sh=function(a){for(var b=[1,1,1,1,2,2,
3,0],c=a.length,d="",f=0;f<c;){var l=a.charCodeAt(f++);if(l&128){var k=b[l>>3&7];if(!(l&64&&k)||f+k>c)return null;for(l&=63>>k;0<k;--k){var n=a.charCodeAt(f++);if(128!=(n&192))return null;l=l<<6|n&63}}d+=String.fromCharCode(l)}return d};h.Sf=function(a){return h.Sh(h.Nc(a))};h.prototype.be=function(){this.devicePixelRatio=window.devicePixelRatio||1;this.He=!!navigator.userAgent.match(/(Windows|Win)/g);this.cd=!!navigator.userAgent.match(/(Mac|Macintosh|Mac_powerpc)/g)&&!navigator.userAgent.match(/(like Mac)/g);
this.Fe=!!navigator.userAgent.match(/(Linux|Ubuntu)/g);this.De=!!navigator.userAgent.match(/(MSIE)/g);this.Be=!!navigator.userAgent.match(/(Edge|EdgA|Edg)/g);this.Ce=!!navigator.userAgent.match(/(Firefox)/g);if(this.hb=!!navigator.userAgent.match(/(Safari)/g)){var a=navigator.userAgent.indexOf("Safari");this.Oa=navigator.userAgent.substring(a+7);a=navigator.userAgent.indexOf("Version");-1!=a&&(this.Oa=navigator.userAgent.substring(a+8));this.Oa=this.Oa.substring(0,this.Oa.indexOf(" "));this.Oa=this.Oa.substring(0,
this.Oa.indexOf("."))}if(this.ec=!!navigator.userAgent.match(/(Chrome|CriOS)/g))this.hb=!1;navigator.userAgent.match(/(SamsungBrowser)/g);if(this.ed=!!navigator.userAgent.match(/(OculusBrowser)/g))this.hb=this.ec=!1;this.ad=!!navigator.userAgent.match(/(iPad|iPhone|iPod)/g);this.bd=!!navigator.userAgent.match(/(iPad)/g)||this.cd&&2<navigator.maxTouchPoints;navigator.userAgent.match(/(iPhone|iPod)/g);this.Zc=!!navigator.userAgent.match(/(android)/i);this.Ee=!!navigator.userAgent.match(/(IEMobile)/i);
this.dd=this.ad||this.Zc||this.Ee||this.bd;/iP(hone|od|ad)/.test(navigator.platform)&&navigator.appVersion.match(/OS (\d+)_(\d+)_?(\d+)?/);this.$c=!window.requestAnimationFrame;try{window.AudioContext=window.AudioContext||window.webkitAudioContext,new AudioContext}catch(c){}this.ka="";a=["Webkit","Moz","O","ms","Ms"];for(var b=0;b<a.length;b++)"undefined"!==typeof document.documentElement.style[a[b]+"Transform"]&&(this.ka="-"+a[b].toLowerCase()+"-")};h.prototype.Me=function(a){var b=document.getElementById("gg_debug");
b&&(b.innerHTML=a+"<br />");window.console&&window.console.log(a)};h.prototype.ph=function(a){this.crossOrigin=a};h.prototype.qh=function(){};h.prototype.xg=function(){return this.oc};h.prototype.nh=function(a){this.Ia=a};h.prototype.he=function(){return this.Ia};h.prototype.jg=function(){return this.dd};h.prototype.le=function(){return this.Kg};h.prototype.th=function(a){this.dd=!!a};h.prototype.hg=function(){return this.isLoaded};h.prototype.ig=function(){return!this.isLoaded};h.prototype.tc=function(a,
b){try{this.oa&&(a=window.innerWidth,b=window.innerHeight);var c=a-this.margin.left.s-this.margin.right.s,d=b-this.margin.top.s-this.margin.bottom.s;if(!(10>c||10>d)){this.T.style.width=c+"px";this.T.style.height=d+"px";this.T.style.left=this.margin.left.s+"px";this.T.style.top=this.margin.top.s+"px";this.W&&(this.W.style.width=a+"px",this.W.style.height=b+"px",this.N.style.width=a+"px",this.N.style.height=b+"px",this.N.width=a,this.N.height=b,this.N.style.left=this.margin.left.s+"px",this.N.style.top=
this.margin.top.s+"px",this.u&&this.u!=this.W&&(this.u.style.width=a+"px",this.u.style.height=b+"px"));this.bc&&(this.v=!0);var f=this.T.offsetWidth,l=this.T.offsetHeight;if(this.P.width!=f||this.P.height!=l)this.P.width=f,this.P.height=l;this.u&&this.u.ggUpdateSize&&this.u.ggUpdateSize(a,b);this.o("sizechanged",{w:a,Bb:b});this.o("playerstatechanged",{})}}catch(k){}};h.prototype.rb=function(){this.zd=!0};h.prototype.Ad=function(){this.hi();this.tc(this.R.offsetWidth,this.R.offsetHeight)};h.prototype.hi=
function(){this.margin.left.qb(this.R.offsetWidth);this.margin.top.qb(this.R.offsetHeight);this.margin.right.qb(this.R.offsetWidth);this.margin.bottom.qb(this.R.offsetHeight)};h.prototype.ve=function(a){void 0===a&&(a=!1);var b={width:0,height:0};b.width=this.P.width+(a?this.margin.left.s+this.margin.right.s:0);b.height=this.P.height+(a?this.margin.top.s+this.margin.bottom.s:0);return b};h.prototype.Fa=function(){var a={x:0,y:0},b=this.T.getBoundingClientRect();a.x=b.left;a.y=b.top;this.hb&&14>Number(this.Oa)&&
(a.x=b.left+window.scrollX,a.y=b.top+window.scrollY);return a};h.prototype.Bh=function(a){this.aa=a};h.prototype.vh=function(a,b,c,d){var f=this,l=!0;"object"===typeof a?(a.hasOwnProperty("left")&&this.margin.left.qc(a.left,a.transition,this.R.offsetWidth),a.hasOwnProperty("top")&&this.margin.top.qc(a.top,a.transition,this.R.offsetHeight),a.hasOwnProperty("right")&&this.margin.right.qc(a.right,a.transition,this.R.offsetWidth),a.hasOwnProperty("bottom")&&this.margin.bottom.qc(a.bottom,a.transition,
this.R.offsetHeight),a.hasOwnProperty("transition")&&a.transition.hasOwnProperty("duration")&&0<a.transition.duration&&(l=!1,this.margin.transition.duration=a.transition.duration,a.transition.hasOwnProperty("timingfunction")?this.margin.transition.timingfunction=a.transition.timingfunction:this.margin.transition.timingfunction="ease")):(this.margin.left.value=a,this.margin.top.value=b,this.margin.right.value=c,this.margin.bottom.value=d);this.aa=this.skinObj;l?this.rb():(b=0,a.transition.hasOwnProperty("delay")&&
(b=a.transition.delay),setTimeout(function(){f.ci(f)},b))};h.prototype.ci=function(a){a.margin.transition.starttime=(new Date).getTime();a.margin.transition.interval&&clearInterval(a.margin.transition.interval);a.margin.transition.interval=setInterval(function(){a.di(a)},20)};h.prototype.di=function(a){var b=((new Date).getTime()-a.margin.transition.starttime)/a.margin.transition.duration;b=Math.max(b,0);b=Math.min(b,1);switch(a.margin.transition.timingfunction){case "ease-in":b=1-Math.cos(b*Math.PI/
2);break;case "ease-out":b=Math.sin(b*Math.PI/2);break;case "ease":b=-(Math.cos(Math.PI*b)-1)/2;break;case "ease-in-out":b=.5>b?4*b*b*b:1-Math.pow(-2*b+2,3)/2;break;case "step-end":b=1==b?1:0}b=Math.round(100*b)/100;a.margin.left.Xb(b,a.R.offsetWidth);a.margin.top.Xb(b,a.R.offsetHeight);a.margin.right.Xb(b,a.R.offsetWidth);a.margin.bottom.Xb(b,a.R.offsetHeight);a.tc(a.R.offsetWidth,a.R.offsetHeight);1<=b&&(clearInterval(a.margin.transition.interval),a.margin.transition.interval=0)};h.prototype.Xd=
function(a){0==a&&(this.i.Db=!1);1==a&&(this.i.Db=!0);2==a&&(this.i.Db=!this.i.Db);this.o("viewmodechanged",{});this.o("playerstatechanged",{})};h.prototype.te=function(){return 1==this.i.Db?1:0};h.prototype.Wd=function(a,b){this.D.mode=1==b&&0<this.D.mode?0:Math.round(a);this.update();this.o("polymodechanged",{})};h.prototype.vf=function(a){var b=this.Fa();this.gb()?(this.I.x=a.clientX-this.margin.left.s,this.I.y=a.clientY-this.margin.top.s):(this.I.x=a.clientX-b.x,this.I.y=a.clientY-b.y)};h.prototype.xb=
function(a){var b=[];a="#"==a.substr(0,1)?a.substr(1):"^"+a+"$";a=new RegExp(a,"");for(var c=0;c<this.G.length;c++)"poly"==this.G[c].type&&a.test(this.G[c].id)&&b.push(this.G[c]);return b};h.prototype.ff=function(a){a=this.xb(a);for(var b=0;b<a.length;b++){var c=this.D.$.indexOf(a[b].id);-1==c?(this.D.$.push(a[b].id),this.D.fa.push(0),this.D.qa.push(1)):this.D.qa[c]=1}this.update()};h.prototype.we=function(a){a=this.xb(a);for(var b=0;b<a.length;b++){var c=this.D.$.indexOf(a[b].id);-1!=c&&(this.D.qa[c]=
0,this.D.uc.push(a[b].id),this.update())}};h.prototype.Yh=function(a){a=this.xb(a);for(var b=0;b<a.length;b++){var c=this.D.$.indexOf(a[b].id);-1==c||-1!=c&&0==this.D.qa[c]?this.ff(a[b].id):this.we(a[b].id);this.update()}};h.prototype.Nf=function(a,b,c,d,f){var l=""==a?this.G:this.xb(a);for(var k=0;k<l.length;k++){var n=l[k];"poly"==n.type&&(n.ja=b,n.Sa=c,n.Ja=d,n.Ta=f)}""==a&&(this.D.ja=b,this.D.Sa=c,this.D.Ja=d,this.D.Ta=f);this.update()};h.prototype.yh=function(a,b){var c=""==a?this.G:this.xb(a);
for(var d=0;d<c.length;d++){var f=c[d];"poly"==f.type&&(f.ac=b)}""==a&&(this.D.ac=b);this.update()};h.prototype.zg=function(){return this.D.mode};h.prototype.Fc=function(){this.o("viewstatechanged",{})};h.prototype.ue=function(){return 0};h.prototype.Mb=function(a,b,c){var d=(new RegExp("%0*"+b,"i")).exec(a.toString());if(d){d=d.toString();var f=c.toString();d.charAt(d.length-1)!=b&&(f=(1+c).toString());if(!isNaN(parseFloat(c)))for(;f.length<d.length-1;)f="0"+f;a=a.replace(d,f)}return a};h.prototype.xd=
function(){this.o("hotspotsupdated",{})};h.prototype.bg=function(){for(var a=[],b=0;b<this.G.length;b++){var c=this.G[b];"point"==c.type&&c.L&&c.L.__div&&a.push(c.L.__div)}return a};h.prototype.Cb=function(a,b){a=Number(a);isNaN(b)&&(b=0);0>b&&(b=0);1<b&&(b=1);return"rgba("+(a>>16&255)+","+(a>>8&255)+","+(a&255)+","+b+")"};h.prototype.Qd=function(){return this.P.width/this.P.height};h.prototype.bb=function(){};h.prototype.update=function(){this.v=!0};h.prototype.kg=function(){return!1};h.prototype.zh=
function(a){this.Lb=a};h.prototype.getQueryParameter=function(){return this.Lb};h.prototype.Rc=function(a){if(a){if("{"==a.charAt(0)||"/"==a.charAt(0)||0<a.indexOf("://")||0==a.indexOf("javascript:"))return a;""!=this.Lb&&(a=-1==a.indexOf("?")?a+("?"+this.Lb):a+("&"+this.Lb));return this.Ia+a}return this.Ia};h.prototype.Zb=function(){return 0};h.prototype.ug=function(){return 0};h.prototype.qd=function(){};h.prototype.Dc=function(){};h.prototype.se=function(){return 0};h.prototype.Fg=function(){return 0};
h.prototype.rd=function(){};h.prototype.Ec=function(){};h.prototype.eb=function(){return 0};h.prototype.Qb=function(){return!1};h.prototype.Bc=function(){return!1};h.prototype.Ye=function(){};h.prototype.uh=function(a){this.bf(a);this.cf(a);this.af(a)};h.prototype.bf=function(a){this.i.ea=!!a};h.prototype.af=function(a){this.i.Xa=!!a};h.prototype.ng=function(){return this.i.Xa};h.prototype.cf=function(a){this.i.jd=!!a};h.prototype.Ig=function(){return this.i.ji};h.prototype.Ih=function(a){this.i.ji=
a};h.prototype.tg=function(){return this.Zc?5:this.bd?6:this.ad?4:this.He?1:this.cd?2:this.Fe?3:0};h.prototype.$f=function(){return this.De?5:this.Be?4:this.Ce?2:this.hb?3:this.ec?1:this.ed?6:0};h.prototype.ag=function(){return window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches?1:0};h.prototype.moveTo=function(){this.F()};h.prototype.Tg=function(){this.F()};h.prototype.Re=function(){};h.prototype.Sg=function(){};h.prototype.Ef=function(){};h.prototype.gi=function(a,b,c){for(var d=
0;d<this.G.length;d++){var f=this.G[d];f.id==a&&(f.pan=b,f.J=c,f.Ji())}this.v=!0};h.prototype.gh=function(a){for(var b=-1,c,d=0;d<this.G.length;d++)c=this.G[d],c.id==a&&(b=d);-1<b&&(c=this.G.splice(b,1).pop(),c.L&&c.L.__div&&this.W.removeChild(c.L.__div))};h.prototype.yg=function(){for(var a=[],b=0;b<this.G.length;b++){var c=this.G[b];"point"==c.type&&a.push(String(c.id))}return a};h.prototype.me=function(){};h.prototype.F=function(){this.hc=(new Date).getTime()};h.prototype.mg=function(){return this.hc};
h.prototype.gb=function(){return document.webkitIsFullScreen||document.mozFullScreen||document.msFullscreenElement&&null!=document.msFullscreenElement||document.fullScreen};h.prototype.Mg=function(a){a=Number(a).toString(16);return a="#000000".substr(0,7-a.length)+a};h.prototype.Og=function(){};h.prototype.pe=function(){return null};h.prototype.pg=function(){return null};h.prototype.Ng=function(){return!1};h.prototype.pc=function(){};h.prototype.Te=function(){};h.prototype.Ue=function(){};h.prototype.kd=
function(){};h.prototype.Df=function(){};h.prototype.sd=function(){};h.prototype.Nh=function(){return 0};h.prototype.Ph=function(){};h.prototype.Oh=function(){};h.prototype.Fh=function(){};h.prototype.Pf=function(){};h.prototype.Xg=function(){};h.prototype.ei=function(){};h.prototype.Xh=function(){};h.prototype.dg=function(){return!1};h.prototype.Cg=function(){return this.Qh};h.prototype.Rh=function(){};h.prototype.wh=function(){};h.prototype.hh=function(){};h.prototype.fg=function(){return!0};h.prototype.ab=
function(a){var b=this.oa!==a;this.oa!==a&&(this.oa=a,this.update(100));if(this.oa){if(this.xf)try{this.m.webkitRequestFullScreen?this.m.webkitRequestFullScreen():this.m.mozRequestFullScreen?this.m.mozRequestFullScreen():this.m.msRequestFullscreen?this.m.msRequestFullscreen():this.m.requestFullScreen?this.m.requestFullScreen():this.m.requestFullscreen&&this.m.requestFullscreen()}catch(c){}this.m.style.position="absolute";a=this.Fa();this.m.style.left=window.pageXOffset-a.x+this.margin.left.s+"px";
this.m.style.top=window.pageYOffset-a.y+this.margin.top.s+"px";document.body.style.overflow="hidden";b&&(this.u&&this.u.ggEnterFullscreen&&this.u.ggEnterFullscreen(),this.o("fullscreenenter",{}),this.o("playerstatechanged",{}))}else{if(this.xf)try{document.webkitIsFullScreen?document.webkitCancelFullScreen():document.mozFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.fullScreen&&(document.cancelFullScreen?document.cancelFullScreen():document.exitFullscreen&&
document.exitFullscreen())}catch(c){}this.m.style.position="relative";this.m.style.left="0px";this.m.style.top="0px";document.body.style.overflow="";b&&(this.u&&this.u.ggExitFullscreen&&this.u.ggExitFullscreen(),this.o("fullscreenexit",{}),this.o("playerstatechanged",{}))}this.rb()};h.prototype.wc=function(){this.ab(!this.oa)};h.prototype.Vf=function(){this.ab(!0)};h.prototype.exitFullscreen=function(){this.ab(!1)};h.prototype.oe=function(){return this.oa};h.prototype.mc=function(){this.oa&&(this.gb()||
this.exitFullscreen(),this.gb()&&(this.m.style.left="0px",this.m.style.top="0px"))};h.prototype.hf=function(){};h.prototype.kf=function(){};h.prototype.rf=function(){};h.prototype.ah=function(){this.F()};h.prototype.jh=function(){};h.prototype.mh=function(){};h.prototype.oh=function(){};h.prototype.Jc=function(){};h.prototype.re=function(){var a=1,b=-1!=navigator.userAgent.indexOf("Mac");window.devicePixelRatio&&b&&(a=window.devicePixelRatio);return{w:screen.width*a,Bb:screen.height*a}};h.prototype.og=
function(){var a=this.re();return a.w>a.Bb?a.w:a.Bb};h.prototype.Wf=function(a){try{var b=a.getAttributeNode("variablename"),c=b.nodeValue.toString();b=a.getAttributeNode("variabletype");var d=Number(b.nodeValue);b=a.getAttributeNode("propertytype");var f=Number(b.nodeValue);b=a.getAttributeNode("defaultvalue");a=void 0;b&&(a=b.nodeValue.toString());this.K[c]={xa:d,Kb:f,Pc:a}}catch(l){console.error(l)}};h.prototype.Xf=function(a){for(var b={},c=a.firstChild;c;){if("custompropertyvalue"==c.nodeName){a=
c.getAttributeNode("value");var d=a.nodeValue.toString();a=c.getAttributeNode("variablename");b[a.nodeValue.toString()]=d}c=c.nextSibling}return b};h.prototype.de=function(a){var b,c="";(b=a.getAttributeNode("id"))&&(c=b.nodeValue.toString());if(!this.Z.hasOwnProperty("object")||!this.Z.object.hasOwnProperty(c)){var d={};for(a=a.firstChild;a;){if("custompropertyvalue"==a.nodeName){b=a.getAttributeNode("variablename");var f=b.nodeValue;b=a.getAttributeNode("value");d[f]=b.nodeValue}a=a.nextSibling}this.Z.object||
(this.Z.object={});this.Z.object[c]=d}};h.prototype.md=function(a,b){a=(new DOMParser).parseFromString(a,"text/xml");this.nd(a,b)};h.prototype.dh=function(a,b,c){try{var d=void 0;d=new XMLHttpRequest;d.open("GET",a,!1);d.send(null);if(d.responseXML){var f=a.lastIndexOf("/");0<=f&&(this.Ia=a.slice(0,f+1));2<=arguments.length&&null!=b&&(this.Ia=b);this.md(d.responseText,c)}else alert("Error loading panorama XML")}catch(l){alert("Error:"+l)}};h.prototype.eh=function(a,b,c,d){var f=new XMLHttpRequest;
var l=this;f.onload=function(k){if(4<=f.readyState)if(f.responseXML){var n=a.lastIndexOf("/");0<=n&&(l.Ia=a.slice(0,n+1));3<=arguments.length&&null!=c&&(l.Ia=c);l.md(f.responseText,d);b&&b()}else alert("Error loading panorama XML");else console.error("Wrong state loading XML:"+f.statusText)};f.onerror=function(){console.error("Error loading XML:"+f.statusText)};f.open("GET",a,!0);f.send(null)};h.prototype.nd=function(){};h.prototype.nc=function(a,b){0<a.length&&".xml"!=a.slice(-4)&&".swf"!=a.slice(-4)&&
"{"!=a.charAt(0)&&window.open(this.Rc(a),b)};h.prototype.ce=function(){};h.prototype.qe=function(){return{}};h.prototype.df=function(){return!0};return h}();y.yc=B})(g||={});
(function(y){var B=function(A){function h(a,b){var c=A.call(this,a,b)||this;c.bj=!1;c.pan={j:0,Ua:0,min:0,max:360,d:0,Ca:0};c.J={j:0,Ua:0,min:-90,max:0,d:0,Ca:0};c.X={j:90,Ua:90,min:1,max:170,$a:0,d:0,mode:0};c.zoom={j:1,Ua:1,min:1,max:1,kc:0,l:-1,d:0,cx:0,cy:0,ic:0,jc:0,viewport:1,Xe:1,jf:0,ae:0,$a:0};c.wa={start:{x:0,y:0},l:{x:0,y:0},pa:{x:0,y:0},j:{x:0,y:0},A:{x:0,y:0}};c.ba={Sc:0,Y:!1,start:{x:0,y:0},l:{x:0,y:0},pa:{x:0,y:0},j:{x:0,y:0},A:{x:0,y:0},startTime:0,ob:null};c.ib=0;c.Ge=!1;c.Fb={enabled:!0,
l:{x:0,y:0},A:{x:0,y:0},X:{active:!1,Tf:0}};c.Wa=!1;c.dc={enabled:!1,Mc:0,Oi:0,td:{enabled:!0,width:180,height:20,ud:0,background:!0,ja:16777215,Ja:0,zc:1,Ac:1,Dd:!0},yi:[]};c.ma={pan:0,J:0,title:"",url:"",target:"",id:"",Mh:"",w:100,Bb:20,Dd:!1,L:null,V:0};c.C=c.ma;c.Bd={};c.U=null;c.va=null;c.Ma=null;c.da=null;c.Ka=null;c.la=null;c.Lc=null;c.ub=null;c.Ei=null;c.Li=null;c.Ai=null;c.sh=!1;c.ze=!1;c.Aa={enabled:!1,delay:5,active:!1,speed:.4,ld:!1,gd:Date.now()};c.tb={active:!1,speed:.1,pan:0,J:0,X:100,
cx:0,cy:0,Ga:0};c.Va=!1;c.ra={title:"",description:"",zi:"",Hi:"",Di:"",source:"",Mi:"",Bi:""};c.Zi=[];c.Zg={target:0,current:0,ta:.01,delay:2,Qc:0,Wb:!1,Jf:!1};c.i={mode:3,Xa:!1,ea:!1,jd:!1,Db:!0,Rd:!0,Ub:!0,Za:!1,Ae:!1,gf:1,Oc:!0,ya:!1,za:!1,Nb:!1,Ob:!1,ha:!1,sensitivity:10,Yd:!1,cc:!1};c.g={x:0,y:0,dx:0,dy:0,width:100,height:100,state:0,Da:-1,Ea:-1,Ba:-1,B:1,H:1,Na:1,mb:0,nb:0,vc:0,path:"images/",ext:"jpg",S:[],ca:512,Pi:1,hd:1,Ke:"",preload:!1};c.Ic={background:!0,ja:0};c.Xc=!1;c.ee=!0;c.Ha=0;
c.Vh=5;c.qf=function(){this.Ha&&this.Ha--;0==this.Ha&&this.u&&this.u.ggLoadedLevels&&this.u.ggLoadedLevels()};c.Eb=!1;c.Lh=function(d,f){this.g.x=d;this.g.y=f;this.bb();this.v=!0};c.Cd=function(d,f){var l=this.eb();this.i.Za?(this.zoom.cx+=d/(this.zoom.j*this.zoom.viewport),this.zoom.cy+=f/(this.zoom.j*this.zoom.viewport)):(this.Ed(-d/20),this.Fd(-f/20));this.pan.Ca+=d*l/this.P.height;this.J.Ca+=f*l/this.P.height;this.pan.j=this.pan.Ca;this.J.j=this.J.Ca;this.bb()};c.Se=function(d){window.MSGesture&&
(this.jb||(this.jb=new window.MSGesture,this.jb.target=this.control),this.jb.addPointer(d.pointerId))};c.Gb=1;c.Gd=function(d){this.i.Nb&&(d=-d);this.g.x+=d;this.bb()};c.Hd=function(d){this.i.Ob&&(d=-d);this.g.y+=d;this.bb()};c.vd=function(d,f,l,k,n,m){var e=this.g,q=e.S.length-1-k,p=e.Ke;p=this.Mb(p,"c",d%e.B+(f%e.H+l%e.Na*e.H)*e.B);p=this.Mb(p,"r",k);p=this.Mb(p,"l",q);p=this.Mb(p,"x",n);p=this.Mb(p,"y",m);return this.Rc(p)};c.bh=function(){var d=this,f=d.g,l,k,n,m;if(0<f.S.length)for(m=0;m<f.S.length;m++){var e=
f.S[m];if(e.cache)for(n=0;n<f.Na;n++)for(k=0;k<f.H;k++)for(l=0;l<f.B;l++){var q=[],p,r;for(r=0;r<e.Rb;r++)for(p=0;p<e.Pa;p++){var t=p+r*e.Pa;var u={};u.g=new Image;u.g.setAttribute("src",d.vd(l,k,n,m,p,r));u.g.onload=function(){d.v=!0;d.Va=!0};q[t]=u;d.La.push(u.g)}e.wd[l+f.B*(k+n*f.H)]=q}}else if(f.preload)for(m=new Image,m.src=d.Yc(f.mb,f.nb,f.vc),n=0;n<f.Na;n++)for(k=0;k<f.H;k++)for(l=0;l<f.B;l++)m=new Image,m.src=d.Yc(l,k,n),d.La.push(m)};c.od=0;c.Yb=!0;c.Ld="aHR0cHM6Ly9vYmplY3QydnIuY29tLw==";
c.Md="Q3JlYXRlZCB3aXRoIE9iamVjdDJWUg==";b&&(b.hasOwnProperty("three")&&(c.Jd=b.three),b.hasOwnProperty("threeLoader")&&(c.Cf=b.threeLoader));c.Me("Object2VR player "+c.Wc()+" - Prefix:  "+c.ka);c.addListener("languagechanged",function(){});c.userdata=c.ra;c.emptyHotspot=c.ma;c.mouse=c.I;c.Pb(c.ma);c.Jc(a);c.Wa&&(c.Ka.style.display="none",c.da.style.display="none",c.Th());c.If();c.F();return c}__extends(h,A);h.prototype.Wc=function(a){return-99991===a?this.Le:"4.0beta2/20670"};h.prototype.ye=
function(){return this.g.Da%this.g.B+(this.g.Ea%this.g.B+this.g.Ba%this.g.Na*this.g.H)*this.g.B};h.prototype.tc=function(a,b){var c=this.P,d=this.margin,f=this.T,l=this.W,k=this.da,n=this.Ka;this.oe()&&("number"==typeof window.innerWidth?(a=window.innerWidth,b=window.innerHeight):document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)?(a=document.documentElement.clientWidth,b=document.documentElement.clientHeight):document.body&&(document.body.clientWidth||
document.body.clientHeight)&&(a=document.body.clientWidth,b=document.body.clientHeight));var m=a-d.left.s-d.right.s,e=b-d.top.s-d.bottom.s;c.width=m;c.height=e;f.style.width=m+"px";f.style.height=e+"px";f.style.left=d.left.s+"px";f.style.top=d.top.s+"px";this.uf();l.style.width=a+"px";l.style.height=b+"px";this.N.style.width=a+"px";this.N.style.height=b+"px";this.N.width=a;this.N.height=b;this.N.style.left=d.left.s+"px";this.N.style.top=d.top.s+"px";k.style.width=a+"px";k.style.height=b+"px";n.style.width=
a+"px";n.style.height=b+"px";if(this.ee){if(!this.la)try{this.Lc=n.getContext("2d"),this.ub=this.la=k.getContext("2d")}catch(q){}try{this.la?(f.removeChild(this.va),f.removeChild(this.U)):(f.removeChild(k),f.removeChild(n))}catch(q){}this.ee=!1}this.la&&(c=window.devicePixelRatio||1,k.width!=Math.round(a*c)||k.height!=Math.round(b*c))&&(k.width=Math.round(a*c),k.height=Math.round(b*c),n.width=Math.round(a*c),n.height=Math.round(b*c),this.la.scale(c,c),this.Lc.scale(c,c),this.Va=this.v=!0);this.v=
!0;this.u&&this.u.ggUpdateSize&&this.u.ggUpdateSize(a,b);this.o("sizechanged",{w:a,Bb:b});this.o("playerstatechanged",{})};h.prototype.Wh=function(){this.Va=this.v=!0;this.Ha&&this.Ha--;0==this.Ha&&this.u&&this.u.ggLoadedLevels&&this.u.ggLoadedLevels()};h.prototype.uf=function(){var a=this,b=a.zoom,c=a.P,d=a.g;var f=a.la;var l=a.ub;var k=a.U;var n=a.va;switch(b.Xe){case 1:b.viewport=Math.min(c.width/d.width,c.height/d.height);break;case 2:b.viewport=Math.max(c.width/d.width,c.height/d.height);break;
case 3:b.viewport=c.width/d.width;break;case 4:b.viewport=c.height/d.height;break;default:b.viewport=1}var m=b.viewport*b.j*(b.cx-d.width/2)+c.width/2;var e=b.viewport*b.j*(b.cy-d.height/2)+c.height/2;m=Math.round(m);e=Math.round(e);var q=Math.round(d.width*b.viewport*b.j);var p=Math.round(d.height*b.viewport*b.j);if(f){if(a.Eb=!1,0<=d.Da&&0<=d.Ea){(q<c.width||p<c.height)&&b.l>b.j&&(l.clear?l.clear():l.clearRect(0,0,a.da.width,a.da.height));if(0<d.S.length){for(var r=0,t=void 0,u=void 0,v=void 0;d.S.length>=
r+2&&d.S[r+1].width>q;)r++;for(var z=r,x=!1;!x;){x=!0;t=d.S[z];n=-m/q*(t.width/d.ca);var w=-e/p*(t.height/d.ca);k=(-m+c.width)/q*(t.width/d.ca);f=(-e+c.height)/p*(t.height/d.ca);n=Math.min(Math.max(0,Math.floor(n)),t.Pa-1);w=Math.min(Math.max(0,Math.floor(w)),t.Rb-1);k=Math.min(Math.max(0,Math.floor(k)),t.Pa-1);f=Math.min(Math.max(0,Math.floor(f)),t.Rb-1);for(v=w;v<=f;v++)for(u=n;u<=k;u++){var C=u+v*t.Pa;(w=t.Qa[C])&&w.g?w.g.complete||(x=!1):x=!1}x||(z+1<d.S.length?z++:x=!0)}for(;z>=r;){t=d.S[z];
n=-m/q*(t.width/d.ca);w=-e/p*(t.height/d.ca);k=(-m+c.width)/q*(t.width/d.ca);f=(-e+c.height)/p*(t.height/d.ca);n=Math.min(Math.max(0,Math.floor(n)),t.Pa-1);w=Math.min(Math.max(0,Math.floor(w)),t.Rb-1);k=Math.min(Math.max(0,Math.floor(k)),t.Pa-1);f=Math.min(Math.max(0,Math.floor(f)),t.Rb-1);for(v=w;v<=f;v++)for(u=n;u<=k;u++)if(C=u+v*t.Pa,(w=t.Qa[C])||(w=t.Qa[C]={}),!w.g&&a.Ha<a.Vh&&(w.g=new Image,w.g.setAttribute("src",a.vd(d.Da,d.Ea,d.Ba,z,u,v)),w.g.onload=function(){a.Wh()},w.g.onerror=function(){a.qf()},
w.g.onabort=function(){a.qf()},0==a.Ha&&a.u&&a.u.ggReLoadedLevels&&a.u.ggReLoadedLevels(),a.Ha++),w.g&&w.g.complete){var E=C=x=void 0,F=void 0;x=m+(-d.hd+d.ca*u)*q/t.width;C=e+(-d.hd+d.ca*v)*p/t.height;E=w.g.width*q/t.width;F=w.g.height*p/t.height;l.drawImage(w.g,x,C,E,F);a.Eb=!0}z--}b.l=b.j;b.ic=b.cx;b.jc=b.cy}else""!=a.U.src&&a.U.complete?(l.clear?l.clear():l.clearRect(0,0,a.da.width,a.da.height),l.drawImage(a.U,m,e,q,p),b.l=b.j,b.ic=b.cx,b.jc=b.cy,a.Eb=!0):a.v=!0;a.Eb&&a.xd()}}else k.setAttribute("width",
d.width+"px"),k.setAttribute("height",d.height+"px"),n.setAttribute("width",d.width+"px"),n.setAttribute("height",d.height+"px"),k.style.left=m+"px",k.style.top=e+"px",k.style.width=q+"px",k.style.height=p+"px",n.style.left=m+"px",n.style.top=e+"px",n.style.width=q+"px",n.style.height=p+"px",b.l=b.j,b.ic=b.cx,b.jc=b.cy};h.prototype.fi=function(){this.T.style.backgroundColor=this.Ic.background?this.Mg(this.Ic.ja):"transparent"};h.prototype.Zb=function(){var a=this.pan;return this.Wa?a.j:a.min+(this.i.ha?
this.g.y/(this.g.H-(this.i.za?0:1)):this.g.x/(this.g.B-(this.i.ya?0:1)))*(a.max-a.min)};h.prototype.vg=function(){return this.Zb()+1};h.prototype.wg=function(){return this.Zb()};h.prototype.qd=function(a){var b=this.pan;this.F();isNaN(a)||(this.Wa?this.pan.j=a:(a=(a-b.min)/(b.max-b.min),this.i.ha?(this.i.za&&(a-=Math.floor(a)),this.g.y=Number(a*(this.g.H-(this.i.za?0:1)))):(this.i.ya&&(a-=Math.floor(a)),this.g.x=Number(a*(this.g.B-(this.i.ya?0:1))))));this.v=!0};h.prototype.Dc=function(a){this.F();
isNaN(a)||this.Ed(a);this.v=!0};h.prototype.se=function(){var a=this.J;return this.Wa?a.j:a.min+(this.i.ha?this.g.x/(this.g.B-(this.i.ya?0:1)):this.g.y/(this.g.H-(this.i.za?0:1)))*(a.max-a.min)};h.prototype.rd=function(a){this.F();this.Wa?this.J.j=a:(a=(a-this.J.min)/(this.J.max-this.J.min),console.log(a),this.i.ha?(this.i.ya&&(a-=Math.floor(a)),this.g.x=Number(a*(this.g.B-(this.i.ya?0:1)))):(this.i.za&&(a-=Math.floor(a)),this.g.y=Number(a*(this.g.H-(this.i.za?0:1)))));this.v=!0};h.prototype.Ec=function(a){this.F();
isNaN(a)||this.Fd(a);this.v=!0};h.prototype.Mf=function(a,b){this.Dc(a,b)};h.prototype.Of=function(a,b){this.Ec(a,b)};h.prototype.eb=function(){return 100*this.zoom.j};h.prototype.Qb=function(a){this.F();this.lb(a/100);return!0};h.prototype.Bc=function(a){return this.Qb(this.eb()-10*a)};h.prototype.Cc=function(a){return this.Qb(this.eb()*Math.exp(-a/50))};h.prototype.Qf=function(a){this.F();this.lb(this.eb()*Math.exp(-a/50)/100)};h.prototype.Hg=function(){return this.zoom.j};h.prototype.lb=function(a){var b=
this.zoom;isNaN(a)||(b.j=a<b.min?b.min:a>b.max?b.max:a);this.v=!0};h.prototype.eg=function(){return 1<this.zoom.max||0<this.zoom.kc};h.prototype.zb=function(){return this.g.Da};h.prototype.Ab=function(){return this.g.Ea};h.prototype.Gh=function(a){isNaN(a)||(this.g.x=Number(a))};h.prototype.Hh=function(a){isNaN(a)||(this.g.y=Number(a))};h.prototype.getState=function(){return this.g.Ba};h.prototype.Tc=function(){return this.g.B};h.prototype.Vc=function(){return this.g.H};h.prototype.Eg=function(){return this.g.Na};
h.prototype.Td=function(a){if(!a&&this.i.ha)return this.Ud(!0);if(this.i.ya)return!0;if(this.i.Nb){if(this.zb()<this.Tc()-1)return!0}else if(0<this.zb())return!0;return!1};h.prototype.Sd=function(a){if(!a&&this.i.ha)return this.Vd(!0);if(this.i.ya)return!0;if(this.i.Nb){if(0<this.zb())return!0}else if(this.zb()<this.Tc()-1)return!0;return!1};h.prototype.Vd=function(a){if(!a&&this.i.ha)return this.Sd(!0);if(this.i.za)return!0;if(this.i.Ob){if(0<this.Ab())return!0}else if(this.Ab()<this.Vc()-1)return!0;
return!1};h.prototype.Ud=function(a){if(!a&&this.i.ha)return this.Td(!0);if(this.i.za)return!0;if(this.i.Ob){if(this.Ab()<this.Vc()-1)return!0}else if(0<this.Ab())return!0;return!1};h.prototype.Kf=function(){return this.zoom.j<this.zoom.max};h.prototype.Lf=function(){return this.zoom.j>this.zoom.min};h.prototype.ie=function(){var a={};a.x=.5-this.zoom.cx/this.g.width;a.y=.5-this.zoom.cy/this.g.height;return a};h.prototype.xh=function(a,b,c){this.F();isNaN(a)||this.qd(a);isNaN(b)||this.rd(b);!isNaN(c)&&
0<c&&this.Qb(c);this.v=!0};h.prototype.Ye=function(){this.g.x=this.g.mb;this.g.y=this.g.nb;this.Fc(this.g.vc,0);this.zoom.j=this.zoom.Ua};h.prototype.moveTo=function(a,b,c,d,f,l){var k=this.tb,n=this.g,m=this.zoom;this.F();this.tb.active=!0;var e=a.toString().split("/");1<e.length&&(a=Number(e[0]),d=b,b=Number(e[1]),2<e.length&&(c=Number(e[2])));k.pan=isNaN(a)?n.x:Number(a);k.J=isNaN(b)?n.y:Number(b);k.X=!isNaN(c)&&0<c?Number(c):100*m.j;k.speed=!isNaN(d)&&0<d?Number(d):1;f&&!isNaN(f)&&l&&!isNaN(l)?
(k.cx=Number(f),k.cy=Number(l),k.Ga=Math.ceil(20/k.speed),0>=k.Ga&&(k.Ga=1)):k.Ga=0};h.prototype.Re=function(a){this.moveTo(this.g.mb,this.g.nb,100*this.zoom.Ua,a)};h.prototype.Af=function(a,b){this.wa.start.x=a;this.wa.start.y=b;this.wa.l.x=a;this.wa.l.y=b;this.Fb.l.x=a;this.Fb.l.y=b;this.pan.Ca=this.pan.j;this.J.Ca=this.J.j};h.prototype.zf=function(a,b){var c=this.wa;c.j.x=a;c.j.y=b;c.A.x=c.j.x-c.l.x;c.A.y=c.j.y-c.l.y;c.l.x=c.j.x;c.l.y=c.j.y};h.prototype.F=function(){this.Aa.active&&(this.Aa.active=
!1,this.o("autorotatechanged",{}),this.g.dx=0,this.g.dy=0);this.tb.active&&(this.tb.active=!1,this.g.dx=0,this.g.dy=0);this.hc=(new Date).getTime()};h.prototype.na=function(a){return a==this.U||a==this.va||a==this.da||a==this.Ka||a==this.control||a==this.N||a.ggType&&"container"==a.ggType?!0:!1};h.prototype.Pe=function(a){var b=a.touches;if(this.ua)this.ua.onclick();this.vf(a);this.i.ea||(a.which&&0!=a.which&&1!=a.which||!this.na(a.target)||(this.Af(a.pageX,a.pageY),b&&(this.ba.Sc=b[0].identifier),
this.ba.Y=!0,this.ba.startTime=(new Date).getTime(),this.F(),a.preventDefault?a.preventDefault():a.returnValue=!1),this.wa.A.x=0,this.wa.A.y=0)};h.prototype.tf=function(a,b){var c=this.D.td,d=this.fb;c.enabled&&(this.C!=this.ma&&0<=a&&0<=b&&""!=this.C.title?(d.innerHTML=this.Ra(this.C.title),d.style.color=this.Cb(c.ud,c.nf),d.style.backgroundColor=c.background?this.Cb(c.ja,c.Sa):"transparent",d.style.border="solid "+this.Cb(c.Ja,c.Ta)+" "+c.Ac+"px",d.style.borderRadius=c.zc+"px",d.style.textAlign=
"center",0<c.width?(d.style.left=a-c.width/2+"px",d.style.width=c.width+"px"):(d.style.width="auto",d.style.left=a-d.offsetWidth/2+"px"),d.style.height=0<c.height?c.height+"px":"auto",d.style.top=b+25+"px",d.style.visibility="inherit",d.style.overflow="hidden"):(d.style.visibility="hidden",d.innerHTML=""))};h.prototype.Pb=function(a){if("string"==typeof a)for(var b=0;b<this.G.length;b++)if(this.G[b].id==a){a=this.G[b];break}this.hotspot=this.C=a&&null!==a&&"object"==typeof a?a:this.ma;this.o("activehotspotchanged",
{hotspot:this.C})};h.prototype.Oe=function(a){var b=this.margin,c=this.i,d=this.dc,f=this.D;this.vf(a);if(1==this.Gb&&!c.ea&&(this.ba.Y&&(this.zf(a.pageX,a.pageY),this.F(),a.preventDefault?a.preventDefault():a.returnValue=!1),0==d.Mc&&this.C==this.ma||"poly"==this.C.type)){c=this.ma;this.na(a.target)&&(c=this.Gc(this.I.x,this.I.y));if(this.C!=c)if(this.C!=this.ma&&(0<this.D.mode&&(this.C.V=0),this.aa&&this.aa.hotspotProxyOut&&this.aa.hotspotProxyOut(this.C.id),this.o("hsproxyout",{id:this.C.id,url:this.C.url})),
c){this.Pb(c);this.aa&&(this.aa.hotspotProxyOver&&this.aa.hotspotProxyOver(this.C.id),this.o("hsproxyover",{id:this.C.id,url:this.C.url}));if("poly"!=this.C.type||0!=this.C.handcursor)this.W.style.cursor="pointer";0<f.mode&&(f.V=1,this.C.V=1,this.v=!0)}else this.Pb(this.ma),this.W.style.cursor="auto",0<f.mode&&(f.V=0,this.v=!0);this.tf(this.I.x-b.left.s,this.I.y-b.top.s)}};h.prototype.Rg=function(a){var b=this,c=b.wa,d=b.ba,f=b.i,l=b.dc;if(!f.ea&&b.ba.Y){b.F();a.preventDefault?a.preventDefault():
a.returnValue=!1;d.Y=!1;c.A.x=0;c.A.y=0;var k=(new Date).getTime(),n=-1;n=Math.abs(c.start.x-c.l.x)+Math.abs(c.start.y-c.l.y);400>k-d.startTime&&0<=n&&20>n&&b.na(a.target)&&(n=Math.abs(c.pa.x-c.l.x)+Math.abs(c.pa.y-c.l.y),a=b.Gc(b.I.x,b.I.y),c.pa.x=c.l.x,c.pa.y=c.l.y,l.enabled&&b.xe(),a?b.sf(a):700>k-b.ib&&0<=n&&20>n?(f.Oc&&setTimeout(function(){b.wc()},10),b.ib=0):b.ib=k)}};h.prototype.Qe=function(a){var b=this.margin,c=this.zoom,d=this.P,f=this.i;if(!f.jd&&this.na(a.target)){var l=a.detail?-1*a.detail:
a.wheelDelta/40;f.Ae&&(l=-l);var k=this.I.x-b.left.s-.5*d.width;b=this.I.y-b.top.s-.5*d.height;d=c.j;this.Cc((0<l?1:-1)*f.gf,!0);f=1/(c.viewport*c.j)-1/(c.viewport*d);c.cx+=k*f;c.cy+=b*f;this.v=!0;a.preventDefault?a.preventDefault():a.returnValue=!1;this.F()}};h.prototype.bi=function(a){var b=this.margin,c=this.zoom,d=this.wa,f=this.ba,l=this.i,k=a.touches,n=this.Fa();this.I.x=k[0].pageX-n.x+b.left.s;this.I.y=k[0].pageY-n.y+b.top.s;if(!l.ea){if(1==k.length&&!f.Y&&k[0]&&(f.startTime=(new Date).getTime(),
f.start.x=k[0].pageX,f.start.y=k[0].pageY,f.l.x=k[0].pageX,f.l.y=k[0].pageY,b=this.ia=k[0].target,this.na(b)&&(this.Af(k[0].pageX,k[0].pageY),f.Sc=k[0].identifier,f.Y=!0,a.preventDefault(),this.F()),b)){l=!1;if(null!=this.ba.ob)for(n=this.ba.ob;n&&n!=this.control;){if(n.onmouseout)n.onmouseout(a);if(n.onmouseleave)n.onmouseleave(a);n=n.parentNode}n=b;for(var m=!0;n&&n!=this.control;)b!=this.ba.ob&&(n.onmouseover&&(n.onmouseover(a),this.na(a)&&(l=!0)),n.onmouseenter&&(n.onmouseenter(a),this.na(a)&&
(l=!0))),n.onmousedown&&(n.onmousedown(a),m=!1,l=!0),n.onclick&&(m=!1),n=n.parentNode;this.ba.ob=m&&b!=this.ba.ob?b:null;l&&a.preventDefault()}1<k.length&&(f.Y=!1);!this.Xc&&2==k.length&&k[0]&&k[1]&&(c.jf=Math.sqrt((k[0].pageX-k[1].pageX)*(k[0].pageX-k[1].pageX)+(k[0].pageY-k[1].pageY)*(k[0].pageY-k[1].pageY)),c.$a=c.j);d.A.x=0;d.A.y=0}};h.prototype.ai=function(a){var b=this.margin,c=this.zoom,d=this.P,f=this.ba,l=this.i,k=a.touches,n=this.Fa();this.I.x=k[0].pageX-n.x+b.left.s;this.I.y=k[0].pageY-
n.y+b.top.s;if(!l.ea){if(1==k.length&&k[0]&&(f.l.x=k[0].pageX,f.l.y=k[0].pageY,f.Y)){a.preventDefault();for(l=0;l<k.length;l++)if(k[l].identifier==f.Sc){this.zf(k[l].pageX,k[l].pageY);break}this.F()}2==k.length&&k[0]&&k[1]&&(f.Y=!1,this.Xc||(c.ae=Math.sqrt((k[0].pageX-k[1].pageX)*(k[0].pageX-k[1].pageX)+(k[0].pageY-k[1].pageY)*(k[0].pageY-k[1].pageY)),f=c.j,this.lb(c.$a/c.jf*c.ae),f=1/(c.viewport*c.j)-1/(c.viewport*f),c.cx+=(this.I.x-b.left.s-.5*d.width)*f,c.cy+=(this.I.y-b.top.s-.5*d.height)*f,a.preventDefault()))}};
h.prototype.$h=function(a){var b=this.ba,c=this.dc,d=!1;if(!this.i.ea){b.Y&&(a.preventDefault(),this.F());var f=(new Date).getTime(),l=void 0,k=!1;l=Math.abs(b.start.x-b.l.x)+Math.abs(b.start.y-b.l.y);if(0<=l&&20>l){d=!0;if(this.ia){var n=this.ia;for(l=function(){if(n.onclick){var e=n;setTimeout(function(){e.onclick(a)},0);"hotspot"!=n.Ki&&(k=!0);d=!1}n=n.parentNode};n&&n!=this.control;)l();l=Math.abs(b.pa.x-b.l.x)+Math.abs(b.pa.y-b.l.y);if(700>f-this.ib&&0<=l&&20>l){if(this.na(this.ia)&&(a.preventDefault(),
this.i.Oc)){var m=this;setTimeout(function(){m.wc()},1)}if(this.ia)for(n=this.ia;n&&n!=this.control;)n.ondblclick&&(n.ondblclick(),k=!0,d=!1),n=n.parentNode;this.ib=0}else this.ib=f;b.pa.x=b.l.x;b.pa.y=b.l.y}(f=this.Gc(this.I.x,this.I.y))&&!d&&(this.sf(f),d=!0);c.enabled&&!d&&this.xe();b.pa.x=b.l.x;b.pa.y=b.l.y}if(this.ia)for(n=this.ia;n&&n!=this.control;)b.ob!=this.ia&&(n.onmouseout&&(n.onmouseout(a),k=!0),n.onmouseleave&&(n.onmouseleave(a),k=!0)),n.onmouseup&&(n.onmouseup(a),k=!0),n=n.parentNode;
k&&a.preventDefault();this.ia=null;b.Y=!1}};h.prototype.Zh=function(a){this.i.ea||(a.preventDefault(),this.ba.Y=!1)};h.prototype.ge=function(a){var b=this.margin,c=this.zoom,d=this.i;this.Xc=!0;this.Gb=1;var f=this.Fa();a.pageX&&(this.I.x=a.pageX-f.x+b.left.s,this.I.y=a.pageY-f.y+b.top.s);d.ea||(a.touches?(this.ia=a.touches.target,this.ia==this.control&&(a.preventDefault(),c.$a=c.j,this.F())):(a.preventDefault(),c.$a=c.j,this.F()))};h.prototype.Yf=function(a){var b=this.margin,c=this.zoom,d=this.P;
if(!this.i.ea&&this.na(a.target)){a.preventDefault();var f=c.j;this.lb(a.scale*c.$a);a=1/(c.viewport*c.j)-1/(c.viewport*f);c.cx+=(this.I.x-b.left.s-.5*d.width)*a;c.cy+=(this.I.y-b.top.s-.5*d.height)*a;this.F()}};h.prototype.Vg=function(a){var b=this.zoom,c=this.P;if(!this.i.ea){var d=this.Fa();if(this.gb()){var f=a.screenX-.5*c.width;c=a.screenY-.5*c.height}else f=a.pageX-d.x-.5*c.width,c=a.pageY-d.y-.5*c.height;a.preventDefault();1!=a.scale&&(this.Gb*=a.scale,a=b.j,this.lb(this.Gb*b.$a),a=1/(b.viewport*
b.j)-1/(b.viewport*a),b.cx+=f*a,b.cy+=c*a,this.F())}};h.prototype.fe=function(a){var b=this.Fb;this.i.ea||(b.X.active=!1,this.na(a.target)&&(a.preventDefault(),this.F(),this.jb&&this.jb.reset&&this.jb.reset()))};h.prototype.Pg=function(a){this.i.Xa||(a=a?a:window.event,this.fc=a.keyCode,this.F())};h.prototype.Qg=function(){this.fc=0;this.i.Xa||this.F()};h.prototype.Yg=function(){this.fc=0;this.i.Xa||this.F()};h.prototype.Ed=function(a){this.i.ha?this.Hd(a):this.Gd(a)};h.prototype.Fd=function(a){this.i.ha?
this.Gd(a):this.Hd(a)};h.prototype.bb=function(){var a=this.g,b=this.zoom,c=this.P,d=this.i;b.kc&&(b.max=a.height/c.height*b.kc);if(d.ya){for(;0>a.x;)a.x+=a.B;for(;a.x>=a.B;)a.x-=a.B}else 0>a.x&&(a.x=0),a.x>=a.B&&(a.x=a.B-1);if(d.za){for(;0>a.y;)a.y+=a.H;for(;a.y>=a.H;)a.y-=a.H}else 0>a.y&&(a.y=0),a.y>=a.H&&(a.y=a.H-1);a.state>=a.Na&&(a.state=a.Na-1);0>a.state&&(a.state=0);b.j=Math.max(b.min,Math.min(b.max,b.j));d.Ub&&(d.Za=1<b.j,this.o("viewmodechanged",{}));c.width>=b.viewport*b.j*a.width?b.cx=
0:(d=(a.width*b.viewport*b.j-c.width)/(b.j*b.viewport*2),b.cx=Math.max(-d,b.cx),b.cx=Math.min(+d,b.cx));c.height>=b.viewport*b.j*a.height?b.cy=0:(a=(a.height*b.viewport*b.j-c.height)/(b.j*b.viewport*2),b.cy=Math.max(-a,b.cy),b.cy=Math.min(+a,b.cy))};h.prototype.Fc=function(a,b){var c=this.g;this.F();c.state!=a&&(c.state=a,0<b&&(a=1/(20*b),this.la?(this.Ka.style.visibility="inherit",this.da.style.transition="opacity "+a+"s linear",this.ub==this.la?(this.da.style.opacity="0.0",this.ub=this.Lc):(this.da.style.opacity=
"1.0",this.ub=this.la)):(this.va.style.visibility="inherit",this.U.style.transition="opacity "+a+"s linear",this.Ma==this.U?(this.U.style.opacity="0.0",this.Ma=this.va):(this.U.style.opacity="1.0",this.Ma=this.U)),this.yd()),this.v=!0)};h.prototype.ue=function(){return this.g.state};h.prototype.Yc=function(a,b,c){return this.Rc(this.g.path+"/img_"+c+"_"+b+"_"+a+"."+this.g.ext)};h.prototype.yd=function(){this.Wa?(this.pf(),this.xd()):(this.bb(),this.ii())};h.prototype.ii=function(){var a=this;if(a.bc){var b,
c,d=a.g,f=a.zoom,l=Math.floor(d.x),k=Math.floor(d.y),n=d.state,m=b=!1;if(d.Da!=l||d.Ea!=k||d.Ba!=n){if(0<d.S.length)for(c=0;c<d.S.length;c++)b=d.S[c],b.cache?b.wd[a.ye()]=b.Qa:b.Qa=[];d.Da=l;d.Ea=k;d.Ba!=n&&(d.Ba=n,m=!0);if(0<d.S.length&&a.la)for(c=0;c<d.S.length;c++)b=d.S[c],b.cache&&(b.Qa=b.wd[a.ye()],b.Qa||(b.Qa=[]));else 0<d.S.length?a.Ma.setAttribute("src",a.vd(l,k,n,d.S.length-1,0,0)):a.Ma.setAttribute("src",a.Yc(l,k,n)),a.Ma.onload=function(){this.Jg=!0;a.v=!0;a.Va=!0},a.Ma.Jg=!1;b=!0}this.i.Rd&&
f.j!=f.l&&1==f.j&&(this.i.Ub=!0,this.o("viewmodechanged",{}));if(b||a.Va||f.j!=f.l||f.cx!=f.ic||f.cy!=f.jc)a.uf(),this.o("positionchanged",{}),a.Va=!1;m&&this.o("viewstatechanged",{})}};h.prototype.$g=function(){var a=this.g,b=this.zoom,c=this.P,d=this.D;if(this.N){if(d.Je!=d.mode||0<d.$.length)d.Je=d.mode,this.N.style.visibility=0<d.mode||0<d.$.length?"inherit":"hidden";if(0<=d.mode||0<this.D.$.length){if(!this.Kc)try{this.Kc=this.N.getContext("2d")}catch(z){}if(this.Kc){var f=this.Kc;if(f.width!=
c.width||f.height!=c.height)f.width=c.width,f.height=c.height;f.clear?f.clear():f.clearRect(0,0,this.N.width,this.N.height);var l=1;0>=d.mode&&(l=0);3==d.mode&&(l=d.M);for(var k=0;k<this.G.length;k++){var n=this.G[k];if("poly"==n.type){var m=l;2==d.mode&&(m=n.M);var e=d.$.indexOf(n.id);-1!=e&&(m=d.fa[e]);for(var q=0;q<n.kb.length;q++){var p=n.kb[q];if((p.Hc==a.Da||n.reuse&1)&&(p.pd==a.Ea||n.reuse&2)&&(p.state==a.Ba||n.reuse&4))for(var r=0;r<p.Ib.length;r++){var t=p.Ib[r];f.fillStyle=this.Cb(n.backgroundcolor,
n.backgroundalpha*m);f.strokeStyle=this.Cb(n.bordercolor,n.borderalpha*m);if(0<t.sa.length){f.beginPath();for(var u=0;u<t.sa.length;u++){var v=t.sa[u];e=b.viewport*b.j*(b.cx+(v.x-.5)*a.width)+.5*c.width;v=b.viewport*b.j*(b.cy+(v.y-.5)*a.height)+.5*c.height;0==u?f.moveTo(e,v):f.lineTo(e,v)}f.closePath();f.stroke();f.fill()}}}}}}}}};h.prototype.Gc=function(a,b){var c=this.margin,d=this.g,f=this.zoom,l=this.P,k=this.D,n=this.G,m=-1;a=((a-c.left.s-.5*l.width)/(f.viewport*f.j)-f.cx)/d.width+.5;b=((b-c.top.s-
.5*l.height)/(f.viewport*f.j)-f.cy)/d.height+.5;for(c=0;c<n.length;c++)if(f=n[c],"poly"==f.type&&f.kb&&(0<=k.mode||0<this.D.$.length&&-1!=this.D.$.indexOf(f.id)))for(l=0;l<f.kb.length;l++){var e=f.kb[l];if((e.Hc==d.Da||f.reuse&1)&&(e.pd==d.Ea||f.reuse&2)&&(e.state==d.Ba||f.reuse&4))for(var q=0;q<e.Ib.length;q++){var p=e.Ib[q];if(0<p.sa.length){var r;var t=!1;var u=0;for(r=p.sa.length-1;u<p.sa.length;r=u++){var v=p.sa[u];r=p.sa[r];v.y>b!=r.y>b&&a<(r.x-v.x)*(b-v.y)/(r.y-v.y)+v.x&&(t=!t)}t&&(m=c)}}}return 0<=
m?n[m]:!1};h.prototype.Ff=function(){for(var a=this.G,b=0;b<a.length;b++)if("point"==a[b].type&&(this.aa&&this.aa.addSkinHotspot&&(a[b].L=new this.aa.addSkinHotspot(a[b])),a[b].L&&a[b].L.__div)){var c=this.W.firstChild;c?this.W.insertBefore(a[b].L.__div,c):this.W.appendChild(a[b].L.__div)}};h.prototype.xd=function(){for(var a=this.G,b=this.margin,c=this.g,d=this.zoom,f=this.P,l=0;l<a.length;l++){var k=a[l],n=void 0,m=void 0;if("point"==k.type){var e=!1;if(this.Wa){var q=new this.Jd.Kd(k.Hb.x,k.Hb.y,
k.Hb.z);this.Ya&&(console.log(q),q.Hf(this.Ug.matrix),console.log(q),q.Hf(this.Ya.matrix),(e=0<=q.z)?(q.length(),q.Si(this.Vb),n=f.width*(.5+q.x/2),m=f.height*(.5-q.y/2)):m=n=0)}else for(q=m=n=0;q<k.locations.length;q++){var p=k.locations[q];(p.column==c.Da||k.reuse&1)&&(p.row==c.Ea||k.reuse&2)&&(p.state==c.Ba||k.reuse&4)&&(e=!0,n=d.viewport*d.j*(d.cx+p.x*c.width-c.width/2)+f.width/2,m=d.viewport*d.j*(d.cy+p.y*c.height-c.height/2)+f.height/2)}k.L&&k.L.__div&&(k.L.__div.style.transition="none",e?(k.L.__div.style.left=
b.left.s+n+"px",k.L.__div.style.top=b.top.s+m+"px",k.L.__div.ggVisible&&(k.L.__div.style.visibility="visible")):(k.L.__div.style.left="-100px",k.L.__div.style.top="-100px",k.L.__div.style.visibility="hidden"))}}this.o("hotspotsupdated",{})};h.prototype.xe=function(){var a=this.dc;0<a.Mc&&(this.nc(this.C.url,this.C.target),this.aa&&this.aa.hotspotProxyClick(a.Mc))};h.prototype.sf=function(a){this.aa&&this.aa.hotspotProxyClick&&this.aa.hotspotProxyClick(a.id);this.o("hsproxyclick",{id:this.C.id,url:this.C.url});
""!=a.url&&(this.nc(a.url,a.target),this.tf(-1,-1))};h.prototype.me=function(a){for(var b=0;b<this.G.length;b++){var c=this.G[b];if(c.id==a)return b={},b.id=a,b.url=c.url,b.target=c.target,b.title=c.title,b.description=c.description,b.skinid=c.Mh,c.Rf&&(b.customimage=c.Rf,b.customimagewidth=c.Gi,b.customimageheight=c.Fi),c.L&&c.L.__div&&(b.div=c.L.__div),b}};h.prototype.Bf=function(){var a=this;setTimeout(function(){a.Bf()},200);5<a.od&&(a.requestAnimationFrame=function(){return function(b){window.setTimeout(b,
10)}},a.$c=!0,a.xc());a.od++};h.prototype.xc=function(){var a=this,b=a.g,c=a.X;var d=a.zoom;var f=a.Fb,l=a.Zg,k=a.tb,n=a.Aa;var m=a.P;var e=a.wa;var q=a.ba,p=a.i,r=a.D,t=a.G,u=Date.now(),v=.01*(u-n.gd);100<v&&(v=100);n.gd=u;this.o("timer",{});this.zd&&(this.Ad(),this.zd=!1);a.$c?setTimeout(function(){a.xc()},1E3/60):requestAnimationFrame(function(){a.xc()});a.od=0;if(q.Y){if(2==p.mode)m=e.l.x-e.start.x,e=e.l.y-e.start.y,a.Cd(m*p.sensitivity/300,e*p.sensitivity/300);else if(3==p.mode){var z=a.Fa(),
x=void 0;u=void 0;p.ha?(u=(e.l.x-z.x)/m.width,x=(e.l.y-z.y)/m.height):(x=(e.l.x-z.x)/m.width,u=(e.l.y-z.y)/m.height);p.Nb&&(x=1-x);p.Ob&&(u=1-u);p=Math.floor((1-x)*b.B);e=Math.floor((1-u)*b.H);0>p&&(p=0);p>=b.B&&(p=b.B-1);0>e&&(e=0);e>=b.H&&(e=b.H-1);a.Lh(p,e)}else f.A.x=.4*(e.l.x-f.l.x),f.A.y=.4*(e.l.y-f.l.y),f.l.x+=f.A.x,f.l.y+=f.A.y,a.Cd(f.A.x*p.sensitivity/10,f.A.y*p.sensitivity/10),f.X.active&&a.Bc(.4*(f.X.Tf-100*d.j));a.v=!0}!f.enabled||0==f.A.x&&0==f.A.y||q.Y||(f.A.x*=.9,f.A.y*=.9,.1>f.A.x*
f.A.x+f.A.y*f.A.y?(f.A.x=0,f.A.y=0):(a.Cd(f.A.x,f.A.y),a.v=!0));if(!a.Ge&&a.bc){for(p=e=0;p<a.La.length;p++)a.La[p].complete&&a.La[p].src!=a.Uf&&e++;a.ze&&(a.ze=!1);e==a.La.length?(a.oc=1,a.Ge=!0,a.u&&a.u.ggLoaded&&a.u.ggLoaded(),this.o("imagesready",{})):a.oc=e/(1*a.La.length);this.o("downloadprogress",{percentLoaded:this.oc})}k.active?(b.dx=k.pan-b.x,b.dy=k.J-b.y,a.X.d=(k.X-100*d.j)/10,c=Math.sqrt(b.dx*b.dx+b.dy*b.dy+c.d*c.d),10*c<k.speed?(k.active=!1,b.dx=0,b.dy=0,a.X.d=0,b.x=Number(k.pan),b.y=
Number(k.J),d.j=k.X/100):(c=c>5*k.speed?k.speed/c:.2,b.dx*=c,b.dy*=c,a.X.d*=c),b.x+=v*b.dx,b.y+=v*b.dy,b.x>=b.B&&(b.x-=b.B,k.pan-=b.B),0>b.x&&(b.x+=b.B,k.pan+=b.B),b.y>=b.H&&(b.y-=b.H,k.J-=b.H),0>b.y&&(b.y+=b.H,k.J+=b.H),d.j+=a.X.d/10,0<k.Ga&&.5>a.X.d&&(f=c=void 0,c=.5-d.cx/b.width,f=.5-d.cy/b.height,m=(k.cx-c)/k.Ga,e=(k.cy-f)/k.Ga,d.cx=(.5-c-m)*b.width,d.cy=(.5-f-e)*b.height,k.Ga--,k.Ga&&(k.active=!0)),d=new Date,a.hc=d.getTime(),a.v=!0):n.active?(b.dx=.95*b.dx+.05*n.speed,b.x+=b.dx*v,n.ld&&(0>b.x||
b.x>=b.B)&&(n.speed=-n.speed,b.dx=-b.dx,b.x+=2*b.dx*v),a.v=!0):(n.enabled&&(d=new Date,d=d.getTime()-a.hc,!q.Y&&0<n.delay&&d>1E3*n.delay&&(n.active=!0,a.o("autorotatechanged",{}),b.dx=0,b.dy=0)),!f.enabled||0!=a.fc||q.Y||0==b.dx&&0==b.dy&&0==a.X.d||(b.dx*=.9,b.dy*=.9,c.d*=.9,b.x+=b.dx,b.y+=b.dy,a.Cc(c.d),1E-4>b.dx*b.dx+b.dy*b.dy&&(b.dx=0,b.dy=0,c.d=0),a.v=!0));l.Jf&&(d=new Date,l.Wb?d.getTime()-l.Qc>=1E3*l.delay&&(l.Wb=!1):(l.current+=l.ta,0>l.current&&(l.current=0,l.ta=-l.ta,l.Wb=!0,l.Qc=d.getTime()),
1<l.current&&(l.current=1,l.ta=-l.ta,l.Wb=!0,l.Qc=d.getTime())));if(0<r.mode||0<r.$.length){if(0<r.$.length){for(p=0;p<r.$.length;p++)r.qa[p]!=r.fa[p]?r.qa[p]>r.fa[p]?(r.fa[p]+=.05,r.qa[p]<r.fa[p]&&(r.fa[p]=r.qa[p])):(r.fa[p]-=.05,r.qa[p]>r.fa[p]&&(r.fa[p]=r.qa[p])):0==r.fa[p]&&-1!=r.uc.indexOf(r.$[p])&&(r.uc.splice(r.uc.indexOf(r.$[p]),1),r.$.splice(p,1),r.qa.splice(p,1),r.fa.splice(p,1));a.v=!0}if(2==r.mode)for(b=0;b<t.length;b++)l=t[b],"poly"==l.type&&l.V!=l.M&&(l.V>l.M?(l.M+=r.ta,l.V<l.M&&(l.M=
l.V)):(l.M-=r.ta,l.V>l.M&&(l.M=l.V)),a.v=!0);3==r.mode&&r.V!=r.M&&(r.V>r.M?(r.M+=r.ta,r.V<r.M&&(r.M=r.V)):(r.M-=r.ta,r.V>r.M&&(r.M=r.V)),a.v=!0)}a.v&&(a.v=!1,a.yd(),a.Eb&&a.$g())};h.prototype.wf=function(){var a=this;setTimeout(function(){a.ab(0)},10);setTimeout(function(){a.ab(0)},100)};h.prototype.If=function(){var a=this;var b=a.W;a.control=b;a.wf();a.Aa.gd=Date.now();setTimeout(function(){a.xc()},10);setTimeout(function(){a.Bf()},200);setTimeout(function(){a.rb();a.yd()},10);b.addEventListener&&
(b.addEventListener("touchstart",function(c){a.bi(c)},!1),b.addEventListener("touchmove",function(c){a.ai(c)},!1),b.addEventListener("touchend",function(c){a.$h(c)},!1),b.addEventListener("touchcancel",function(c){a.Zh(c)},!1),b.addEventListener("pointerdown",function(c){a.Se(c)},!1),b.addEventListener("MSPointerDown",function(c){a.Se(c)},!1),b.addEventListener("MSGestureStart",function(c){a.ge(c)},!1),b.addEventListener("MSGestureEnd",function(c){a.fe(c)},!1),b.addEventListener("MSGestureChange",
function(c){a.Vg(c)},!1),b.addEventListener("gesturestart",function(c){a.ge(c)},!1),b.addEventListener("gesturechange",function(c){a.Yf(c)},!1),b.addEventListener("gestureend",function(c){a.fe(c)},!1),b.addEventListener("mousedown",function(c){a.Pe(c)},!1),b.addEventListener("mousemove",function(c){a.Oe(c)},!1),a.U.addEventListener("mousedown",function(c){a.Pe(c)},!1),a.U.addEventListener("mousemove",function(c){a.Oe(c)},!1),document.addEventListener("mouseup",function(c){a.Rg(c)},!1),b.addEventListener("mousewheel",
function(c){a.Qe(c)},!1),b.addEventListener("DOMMouseScroll",function(c){a.Qe(c)},!1),document.addEventListener("keydown",function(c){a.Pg(c)},!1),document.addEventListener("keyup",function(){a.Qg()},!1),window.addEventListener("orientationchange",function(){a.wf()},!1),window.addEventListener("resize",function(){a.rb()},!1),window.addEventListener("blur",function(){a.Yg()},!1),a.m.addEventListener("webkitfullscreenchange",function(){a.mc()},!1),document.addEventListener("mozfullscreenchange",function(){a.mc()},
!1),window.addEventListener("webkitfullscreenchange",function(){a.mc()},!1),document.addEventListener("MSFullscreenChange",function(){a.mc()},!1));b.oncontextmenu=function(c){void 0===c&&(c=window.event);return c.target&&!a.na(c.target)?!0:c.ctrlKey?!0:(c=a.rg(c),a.Jh(c.x,c.y),!1)}};h.prototype.ab=function(a){var b=this.margin;this.oa!=a&&(this.oa=a,this.Va=this.v=!0);if(this.oa){try{this.m.webkitRequestFullScreen?this.m.webkitRequestFullScreen():this.m.mozRequestFullScreen?this.m.mozRequestFullScreen():
this.m.msRequestFullscreen?this.m.msRequestFullscreen():this.m.requestFullScreen?this.m.requestFullScreen():this.m.requestFullscreen&&this.m.requestFullscreen()}catch(f){}this.m.style.position="absolute";a=this.Fa();var c=0,d=0;"number"==typeof window.pageYOffset?(d=window.pageYOffset,c=window.pageXOffset):document.body&&(document.body.scrollLeft||document.body.scrollTop)?(d=document.body.scrollTop,c=document.body.scrollLeft):document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)&&
(d=document.documentElement.scrollTop,c=document.documentElement.scrollLeft);this.m.style.left=Math.round(c-a.x+b.left.s)+"px";this.m.style.top=Math.round(d-a.y+b.top.s)+"px";document.body.style.overflow="hidden";this.u&&this.u.ggEnterFullscreen&&this.u.ggEnterFullscreen();this.o("fullscreenenter",{})}else{try{document.webkitIsFullScreen?document.webkitCancelFullScreen():document.mozFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.fullScreen&&
(document.cancelFullScreen?document.cancelFullScreen():document.exitFullscreen&&document.exitFullscreen())}catch(f){}this.m.style.position="relative";this.m.style.left="0px";this.m.style.top="0px";document.body.style.overflow="";this.u&&this.u.ggExitFullscreen&&this.u.ggExitFullscreen();this.o("fullscreenexit",{})}this.o("playerstatechanged",{});this.rb()};h.prototype.hf=function(a,b,c){var d=this.Aa;d.enabled=!0;d.active=!0;a&&0!=a&&(d.speed=a);b&&(d.delay=b);c&&(d.ld=1==c);this.o("autorotatechanged",
{})};h.prototype.kf=function(){var a=this.Aa;a.active=!1;a.enabled=!1;this.o("autorotatechanged",{})};h.prototype.rf=function(){var a=this.Aa;a.enabled=!a.active;a.active=a.enabled;this.o("autorotatechanged",{})};h.prototype.gg=function(){return this.Aa.active};h.prototype.Xd=function(a){0==a&&(this.i.Za=!1);1==a&&(this.i.Za=!0);2==a&&(this.i.Za=this.i.Za?!1:!0);this.i.Ub=3==a;this.o("viewmodechanged",{});this.o("playerstatechanged",{})};h.prototype.te=function(){return 1==this.i.Za?1:0};h.prototype.cb=
function(a){var b=this,c=[];a="#"==a.substr(0,1)?a.substr(1):"^"+a+"$";var d=new RegExp(a,"");Object.keys(this.Bd).forEach(function(f){d.test(f)&&c.push(b.Bd[f])});return c};h.prototype.pe=function(a){a=this.cb(a);return 0<a.length?a[0]:null};h.prototype.fh=function(a,b){var c=this;b.addEventListener("ended",function(d){c.o("videoended",{video:d.target})});b.addEventListener("pause",function(d){c.o("videopaused",{video:d.target})});b.addEventListener("play",function(d){c.o("videostarted",{video:d.target})});
this.Bd[a]=b};h.prototype.pc=function(a){var b=null;a=this.cb(a);for(var c=0;c<a.length;c++)b=a[c].play();return b};h.prototype.Te=function(a,b){for(var c=this.cb(a),d=0;d<c.length;d++)c[d].paused?this.pc(a,b):this.kd(a)};h.prototype.Ue=function(a,b){for(var c=this.cb(a),d=0;d<c.length;d++)c[d].paused?this.pc(a,b):this.sd(a)};h.prototype.kd=function(a){try{var b=void 0,c=this.cb(a);for(b=0;b<c.length;b++)c[b].pause()}catch(d){}};h.prototype.sd=function(a){var b;try{var c=this.cb(a);for(b=0;b<c.length;b++){var d=
c[b];d.pause();d.currentTime=0}}catch(f){}};h.prototype.Jh=function(a,b){var c=this,d=[];if(c.i.Yd){var f={style:"text-align: left;margin: 0;padding: 5px 20px;vertical-align: left;cursor: pointer;",onclick:function(){c.wc()}};f.innerHTML=c.gb()?this.Ra("Exit Fullscreen"):this.Ra("Enter Fullscreen");d.push(f)}c.Kh(a,b,d)};h.prototype.Jc=function(a){var b=this.sh;(this.R=document.getElementById(a))?(this.R.innerHTML="",this.m=document.createElement("div"),b&&this.m.setAttribute("id","viewport"),this.m.setAttribute("style",
"top:\t0px;left: 0px;-ms-touch-action: none;touch-action: none;position:relative;max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.R.appendChild(this.m),this.T=document.createElement("div"),b&&this.T.setAttribute("id","viewer"),a="top:\t0px;left: 0px;overflow: hidden;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.ka+"user-select: none;"),this.T.setAttribute("style",
a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.m.appendChild(this.T),this.va=document.createElement("img"),b&&this.va.setAttribute("id","objectimage2"),this.va.setAttribute("galleryimg","false"),a="top:\t0px;left: 0px;position:absolute;visibility: hidden;-ms-touch-action: none;touch-action: none;"+(this.ka+"user-select: none;"),this.va.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),
this.T.appendChild(this.va),this.U=document.createElement("img"),b&&this.U.setAttribute("id","objectimage"),this.U.setAttribute("galleryimg","false"),a="top:\t0px;left: 0px;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.ka+"user-select: none;"),this.U.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.T.appendChild(this.U),this.Ma=this.U,this.Ka=
document.createElement("canvas"),b&&this.Ka.setAttribute("id","objectcanvas2"),a="top:\t0px;left: 0px;width:  100px;height: 100px;visibility: hidden;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.ka+"user-select: none;"),this.Ka.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.T.appendChild(this.Ka),this.da=document.createElement("canvas"),
b&&this.da.setAttribute("id","objectcanvas"),a="top:\t0px;left: 0px;width:  100px;height: 100px;position:absolute;-ms-touch-action: none;touch-action: none;"+(this.ka+"user-select: none;"),this.da.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.T.appendChild(this.da),this.fb=document.createElement("div"),b&&this.fb.setAttribute("id","hotspottext"),this.fb.setAttribute("style",
"top:\t0px;left: 0px;position:absolute;padding: 3px;visibility: hidden;z-index: 1100;"),this.fb.innerHTML=" Hotspot text!",this.T.appendChild(this.fb),this.W=document.createElement("div"),b&&this.W.setAttribute("id","hotspots"),a="top:\t0px;left: 0px;width:  100px;height: 100px;overflow: hidden;position:absolute;z-index: 1000;"+(this.ka+"user-select: none;"),this.W.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),
this.m.appendChild(this.W),this.N=document.createElement("canvas"),b&&this.N.setAttribute("id","hotspotcanvas"),a="top:\t0px;left: 0px;width:  100px;height: 100px;overflow: hidden;position:absolute;z-index: 900;"+(this.ka+"user-select: none;"),this.N.setAttribute("style",a+"max-width: none !important;max-height: none !important;min-width: none !important;min-height: none !important;padding 0px !important;margin 0px !important;"),this.m.appendChild(this.N),this.divSkin=this.u=this.W):alert("container not found!")};
h.prototype.nd=function(a){this.Pb(this.ma);var b=this.Fb,c=this.Ic,d=this.g,f=this.zoom,l=this.i,k=this.Aa,n=this.D,m=a.firstChild;a=m.firstChild;null==a&&(a=m.nextSibling.firstChild);for(var e;a;){"customproperty"==a.nodeName&&this.Wf(a);if("view"==a.nodeName)for(m=a.firstChild;m;){"start"==m.nodeName&&(e=m.getAttributeNode("column"),d.mb=Number(e?e.nodeValue:0),d.x=d.mb,e=m.getAttributeNode("row"),d.nb=Number(e?e.nodeValue:0),d.y=d.nb,e=m.getAttributeNode("state"),d.vc=Number(e?e.nodeValue:0),
d.state=d.vc);"zoom"==m.nodeName&&(e=m.getAttributeNode("min"),f.min=1*(e?e.nodeValue:1),e=m.getAttributeNode("default"),f.Ua=1*(e?e.nodeValue:1),f.j=f.Ua,e=m.getAttributeNode("max"),f.max=1*(e?e.nodeValue:1),e=m.getAttributeNode("maxpixel"),f.kc=1*(e?e.nodeValue:0),e=m.getAttributeNode("centerx"),f.cx=1*(e?e.nodeValue:0),e=m.getAttributeNode("centery"),f.cy=1*(e?e.nodeValue:0));"limits"==m.nodeName&&(e=m.getAttributeNode("panmin"),this.pan.min=1*(e?e.nodeValue:0),e=m.getAttributeNode("panmax"),this.pan.max=
1*(e?e.nodeValue:360),e=m.getAttributeNode("tiltmin"),this.J.min=1*(e?e.nodeValue:0),e=m.getAttributeNode("tiltmax"),this.J.max=1*(e?e.nodeValue:90));if("viewer"==m.nodeName){if(e=m.getAttributeNode("background"))c.background=1==e.nodeValue;if(e=m.getAttributeNode("backgroundcolor"))c.ja=1*e.nodeValue;if(e=m.getAttributeNode("imagescaling"))f.Xe=1*e.nodeValue}m=m.nextSibling}if("autorotate"==a.nodeName){this.Yb&&(k.enabled=!1);if(e=a.getAttributeNode("start"))k.enabled=1==e.nodeValue;if(e=a.getAttributeNode("pingpong"))k.ld=
1==e.nodeValue;if(e=a.getAttributeNode("speed"))k.speed=1*e.nodeValue;if(e=a.getAttributeNode("delay"))k.delay=1*e.nodeValue;k.active=k.enabled;(e=a.getAttributeNode("onlyonce"))&&0<e.nodeValue&&(m=d.mb,m=0<k.speed?m+(e.nodeValue*d.B+.5):m-(e.nodeValue*d.B+.5),this.moveTo(m,d.nb,0,Math.abs(k.speed)))}if("input"==a.nodeName){if(e=a.getAttributeNode("columns"))d.B=1*e.nodeValue;if(e=a.getAttributeNode("rows"))d.H=1*e.nodeValue;if(e=a.getAttributeNode("states"))d.Na=1*e.nodeValue;if(e=a.getAttributeNode("width"))d.width=
1*e.nodeValue;if(e=a.getAttributeNode("height"))d.height=1*e.nodeValue;if(e=a.getAttributeNode("fileextension"))d.ext=e.nodeValue;if(e=a.getAttributeNode("imagepath"))d.path=e.nodeValue;if(e=a.getAttributeNode("leveltileurl"))d.Ke=e.nodeValue;if(e=a.getAttributeNode("leveltilesize"))d.ca=Number(e.nodeValue);if(e=a.getAttributeNode("overlap"))d.hd=e.nodeValue;if(e=a.getAttributeNode("preload"))d.preload=1==e.nodeValue;d.S=[];for(m=a.firstChild;m;){if("level"==m.nodeName){var q={};e=m.getAttributeNode("width");
q.width=1*(e?e.nodeValue:1);e=m.getAttributeNode("height");q.height=1*(e?e.nodeValue:1);e=m.getAttributeNode("preload");q.cache=!1;e&&(q.cache=1==e.nodeValue);q.Pa=Math.floor((q.width+d.ca-1)/d.ca);q.Rb=Math.floor((q.height+d.ca-1)/d.ca);q.Qa=[];q.wd=[];d.S.push(q)}m=m.nextSibling}}if("control"==a.nodeName&&this.Yb){if(e=a.getAttributeNode("simulatemass"))b.enabled=1==e.nodeValue;if(e=a.getAttributeNode("locked"))l.ea=1==e.nodeValue;e&&(l.Xa=1==e.nodeValue);if(e=a.getAttributeNode("lockedmouse"))l.ea=
1==e.nodeValue;if(e=a.getAttributeNode("lockedkeyboard"))l.Xa=1==e.nodeValue;if(e=a.getAttributeNode("lockedwheel"))l.jd=1==e.nodeValue;if(e=a.getAttributeNode("invertwheel"))l.Ae=1==e.nodeValue;if(e=a.getAttributeNode("speedwheel"))l.gf=1*e.nodeValue;if(e=a.getAttributeNode("sensitifity"))l.sensitivity=1*e.nodeValue;if(e=a.getAttributeNode("sensitivity"))l.sensitivity=1*e.nodeValue;if(e=a.getAttributeNode("wrapx"))l.ya=1==e.nodeValue;if(e=a.getAttributeNode("wrapy"))l.za=1==e.nodeValue;if(e=a.getAttributeNode("revx"))l.Nb=
1==e.nodeValue;if(e=a.getAttributeNode("revy"))l.Ob=1==e.nodeValue;if(e=a.getAttributeNode("swapxy"))l.ha=1==e.nodeValue;if(e=a.getAttributeNode("dblclickfullscreen"))l.Oc=1==e.nodeValue;if(e=a.getAttributeNode("automovemode"))l.Ub=l.Rd=1==e.nodeValue;if(e=a.getAttributeNode("controller"))l.mode=1*e.nodeValue;if(e=a.getAttributeNode("contextfullscreen"))this.i.Yd=1==e.nodeValue;if(e=a.getAttributeNode("hideabout"))this.i.cc=1==e.nodeValue;for(m=a.firstChild;m;)"menulink"==m.nodeName&&(q={text:"",
url:""},e=m.getAttributeNode("text"),q.text=e.nodeValue,e=m.getAttributeNode("url"),q.url=e.nodeValue,this.lc.push(q)),m=m.nextSibling}if("hotspots"==a.nodeName)for(m=a.firstChild;m;){if("label"==m.nodeName){q=n.td;if(e=m.getAttributeNode("enabled"))q.enabled=1==e.nodeValue;if(e=m.getAttributeNode("width"))q.width=1*e.nodeValue;if(e=m.getAttributeNode("height"))q.height=1*e.nodeValue;if(e=m.getAttributeNode("textcolor"))q.ud=1*e.nodeValue;if(e=m.getAttributeNode("textalpha"))q.nf=1*e.nodeValue;if(e=
m.getAttributeNode("background"))q.background=1==e.nodeValue;if(e=m.getAttributeNode("backgroundalpha"))q.Sa=1*e.nodeValue;if(e=m.getAttributeNode("backgroundcolor"))q.ja=1*e.nodeValue;if(e=m.getAttributeNode("border"))q.Ac=1*e.nodeValue;if(e=m.getAttributeNode("bordercolor"))q.Ja=1*e.nodeValue;if(e=m.getAttributeNode("borderalpha"))q.Ta=1*e.nodeValue;if(e=m.getAttributeNode("borderradius"))q.zc=1*e.nodeValue;if(e=m.getAttributeNode("wordwrap"))q.Dd=1==e.nodeValue}if("polystyle"==m.nodeName){if(e=
m.getAttributeNode("mode"))n.mode=1*e.nodeValue;if(e=m.getAttributeNode("bordercolor"))n.Ja=1*e.nodeValue;if(e=m.getAttributeNode("backgroundcolor"))n.ja=1*e.nodeValue;if(e=m.getAttributeNode("borderalpha"))n.Ta=1*e.nodeValue;if(e=m.getAttributeNode("backgroundalpha"))n.Sa=1*e.nodeValue;if(e=m.getAttributeNode("handcursor"))this.D.ac=1==e.nodeValue}if("hotspot"==m.nodeName){var p={type:"point",pan:0,tilt:0,url:"",target:"",id:"",skinid:"",w:100,h:20,customimage:"",customimagewidth:0,customimageheight:0,
obj3d:{x:0,y:0,z:0},wordwrap:!1,obj:null,sa:null};(e=m.getAttributeNode("url"))&&(p.url=e.nodeValue.toString());(e=m.getAttributeNode("target"))&&(p.target=e.nodeValue.toString());(e=m.getAttributeNode("title"))&&(p.title=e.nodeValue.toString());(e=m.getAttributeNode("description"))&&(p.description=e.nodeValue.toString());(e=m.getAttributeNode("id"))&&(p.id=e.nodeValue.toString());(e=m.getAttributeNode("reuse"))&&(p.reuse=Number(e.nodeValue));(e=m.getAttributeNode("skinid"))&&(p.skinid=e.nodeValue.toString());
if(e=m.getAttributeNode("x"))p.Hb.x=parseFloat(e.nodeValue.toString());if(e=m.getAttributeNode("y"))p.Hb.y=parseFloat(e.nodeValue.toString());if(e=m.getAttributeNode("z"))p.Hb.z=parseFloat(e.nodeValue.toString());(e=m.getAttributeNode("customimage"))&&(p.customimage=this.he()+e.nodeValue);(e=m.getAttributeNode("customimagewidth"))&&(p.customimagewidth=Number(e.nodeValue));(e=m.getAttributeNode("customimageheight"))&&(p.customimageheight=Number(e.nodeValue));(e=a.getAttributeNode("width"))&&(p.w=e.nodeValue.toString());
(e=a.getAttributeNode("height"))&&(p.h=e.nodeValue.toString());(e=a.getAttributeNode("wordwrap"))&&(p.wordwrap=1==e.nodeValue);p.locations=[];for(q=m.firstChild;q;){if("location"==q.nodeName){var r={column:0,row:0,state:0,x:0,y:0};(e=q.getAttributeNode("column"))&&(r.column=Number(e.nodeValue));(e=q.getAttributeNode("row"))&&(r.row=Number(e.nodeValue));(e=q.getAttributeNode("state"))&&(r.state=Number(e.nodeValue));(e=q.getAttributeNode("x"))&&(r.x=Number(e.nodeValue));(e=q.getAttributeNode("y"))&&
(r.y=Number(e.nodeValue));p.locations.push(r)}q=q.nextSibling}this.G.push(p);this.de(m)}if("polyhotspot"==m.nodeName){p={type:"poly",url:"",target:"",id:"",skinid:"",reuse:0,w:100,h:20,wordwrap:!1,obj:null,sa:null,M:0,V:0};(e=m.getAttributeNode("url"))&&(p.url=e.nodeValue.toString());(e=m.getAttributeNode("target"))&&(p.target=e.nodeValue.toString());(e=m.getAttributeNode("title"))&&(p.title=e.nodeValue.toString());(e=m.getAttributeNode("id"))&&(p.id=e.nodeValue.toString());(e=m.getAttributeNode("reuse"))&&
(p.reuse=Number(e.nodeValue));p.bordercolor=n.Ja;p.backgroundcolor=n.ja;p.borderalpha=n.Ta;p.backgroundalpha=n.Sa;p.handcursor=n.ac;(e=m.getAttributeNode("bordercolor"))&&(p.bordercolor=1*e.nodeValue);(e=m.getAttributeNode("backgroundcolor"))&&(p.backgroundcolor=1*e.nodeValue);(e=m.getAttributeNode("borderalpha"))&&(p.borderalpha=1*e.nodeValue);(e=m.getAttributeNode("backgroundalpha"))&&(p.backgroundalpha=1*e.nodeValue);p.kb=[];for(q=m.firstChild;q;){if("polygon"==q.nodeName){r={Hc:0,pd:0,state:0,
yf:""};if(e=q.getAttributeNode("vertices")){r.yf=e.nodeValue.toString();e=r.yf.split("|");r.Ib=[];for(var t=0;t<e.length;t++){var u={},v=e[t].split(";");u.sa=[];for(var z=0;z<v.length;z++){var x=v[z].split(","),w={};w.x=1*x[0];w.y=1*x[1];u.sa.push(w)}r.Ib.push(u)}}if(e=q.getAttributeNode("column"))r.Hc=e.nodeValue;if(e=q.getAttributeNode("row"))r.pd=e.nodeValue;if(e=q.getAttributeNode("state"))r.state=e.nodeValue;p.kb.push(r)}q=q.nextSibling}this.G.push(p);this.de(m)}m=m.nextSibling}"userdata"==a.nodeName&&
(e=a.getAttributeNode("title"),this.ra.title=e?e.nodeValue.toString():"",e=a.getAttributeNode("description"),this.ra.description=e?e.nodeValue.toString():"",e=a.getAttributeNode("author"),this.ra.author=e?e.nodeValue.toString():"",e=a.getAttributeNode("datetime"),this.ra.datetime=e?e.nodeValue.toString():"",e=a.getAttributeNode("copyright"),this.ra.copyright=e?e.nodeValue.toString():"",e=a.getAttributeNode("source"),this.ra.source=e?e.nodeValue.toString():"",e=a.getAttributeNode("info"),this.ra.information=
e?e.nodeValue.toString():"",e=a.getAttributeNode("comment"),this.ra.comment=e?e.nodeValue.toString():"",this.sb.object=this.Xf(a));if("translations"==a.nodeName){for(m=a.firstChild;m;){"json"==m.nodeName&&this.Nd(m.textContent);if("projecttranslation"==m.nodeName){e={};if(q=m.getAttributeNode("langcode"))e.langCode=q.nodeValue;if(q=m.getAttributeNode("langname"))e.langName=q.nodeValue;this.Ve.push(e)}m=m.nextSibling}this.Ie||this.$e(window.navigator.language)}a=a.nextSibling}this.Ff();this.v=!0;this.Yb&&
this.u&&this.u.ggViewerInit&&this.u.ggViewerInit();this.Yb=!1;this.o("viewerinit",{});this.bc=!0;this.rb();this.fi();this.bh();this.o("configloaded",{});this.o("playerstatechanged",{})};h.prototype.Th=function(){var a=this,b=a.Jd,c=a.T;(a.Vb=new b.vi(90,window.innerWidth/window.innerHeight,.05,20)).position.set(0,0,1);var d=a.rc=new b.wi,f=new b.ti(11657727,12155424,1);d.add(f);d.background=new b.ni(3355443);(new a.Cf).Wi("gnome/").load("model.gltf",function(l){l.rc.cj(function(e){e.Ni&&(e.Qi.Yi=
b.oi)});l=a.Ug=l.rc;var k=a.Ya=new b.si;k.add(l);new b.mi(.5,.5,.5);new b.ui({color:13421772,fj:!0});a.rc.add(k);k=(new b.li).rh(l);var n=k.ie(new b.Kd),m=k.Bg(new b.Kd);console.log(n,m);l.kh(-90/(180/Math.PI));l.scale.Wg(1/Math.max(m.x,m.y,m.z));k.rh(l);k.ie();k.Bg(m);l.position.Ci(n).Wg(-1);a.update()});d=a.We=new b.xi({antialias:!0});d.Xi(window.devicePixelRatio);d.Ah(window.innerWidth,window.innerHeight);d.$i=b.ki;d.aj=1;d.Ri=b.Vi;c.appendChild(d.Ii);window.addEventListener("resize",function(){a.Uh()})};
h.prototype.Uh=function(){console.log("resize");this.Vb.Qd=this.Qd();this.Vb.ej();var a=this.ve();this.We.Ah(a.width,a.height);this.pf()};h.prototype.pf=function(){this.Ya&&(this.Ya.rotation.set(0,0,0),this.Ya.dj(),this.Ya.kh(this.J.j*Math.PI/180),this.Ya.Ui(this.pan.j*Math.PI/180));this.We.Ti(this.rc,this.Vb)};h.prototype.nc=function(a,b){0<a.length&&window.open(a,b)};h.prototype.sg=function(){return this.ra};h.prototype.ce=function(){};h.prototype.qe=function(){return{}};h.prototype.df=function(){return!0};
return h}(y.yc);y.Id=B})(g||={});window.object2vrPlayer=g.Id;var D=g.Id.prototype;D._=D.Ra;D.setContainer=D.oh;D.setLanguage=D.$e;D.getLanguage=D.lg;D.addTranslations=D.Nd;D.getProjectTranslations=D.Ag;D.getVersion=D.Wc;D.readConfigString=D.md;D.readConfigUrl=D.dh;D.readConfigUrlAsync=D.eh;D.readConfigXml=D.nd;D.openUrl=D.nc;D.setMargins=D.vh;D.addListener=D.addListener;D.on=D.addListener;D.removeEventListener=D.removeEventListener;D.off=D.removeEventListener;D.detectBrowser=D.be;
D.getCurrentNode=D.yb;D.getPercentLoaded=D.xg;D.setBasePath=D.nh;D.getBasePath=D.he;D.setViewerSize=D.tc;D.getViewerSize=D.ve;D.updateViewerSizeNow=D.Ad;D.setSkinObject=D.Bh;D.changeViewMode=D.Xd;D.getViewMode=D.te;D.changePolygonMode=D.Wd;D.setPolygonMode=D.Wd;D.getPolygonMode=D.zg;D.showOnePolyHotspot=D.ff;D.hideOnePolyHotspot=D.we;D.changePolyHotspotColor=D.Nf;D.setPolyHotspotHandcursor=D.yh;D.toggleOnePolyHotspot=D.Yh;D.changeViewState=D.Fc;D.getViewState=D.ue;D.isTouching=D.Og;
D.getIsMobile=D.jg;D.setIsMobile=D.th;D.getHasTouch=D.le;D.getIsAutorotating=D.gg;D.getIsLoading=D.ig;D.getIsLoaded=D.hg;D.getIsTileLoading=D.kg;D.getLastActivity=D.mg;D.getPan=D.Zb;D.getPanN=D.vg;D.getPanNorth=D.wg;D.getPanDest=D.ug;D.setPan=D.qd;D.changePan=D.Dc;D.changePanLog=D.Mf;D.getTilt=D.se;D.getTiltDest=D.Fg;D.setTilt=D.rd;D.changeTilt=D.Ec;D.changeTiltLog=D.Of;D.getFov=D.eb;D.setFov=D.Qb;D.changeFov=D.Bc;D.changeFovLog=D.Cc;D.setPanTiltFov=D.xh;D.getZoom=D.Hg;D.setZoom=D.lb;
D.changeZoom=D.Qf;D.getHasZoom=D.eg;D.setDefaultView=D.Ye;D.getX=D.zb;D.getY=D.Ab;D.setX=D.Gh;D.setY=D.Hh;D.getState=D.getState;D.getColumnsCount=D.Tc;D.getRowsCount=D.Vc;D.getStatesCount=D.Eg;D.canPanRight=D.Td;D.canPanLeft=D.Sd;D.canTiltUp=D.Vd;D.canTiltDown=D.Ud;D.canZoomIn=D.Kf;D.canZoomOut=D.Lf;D.setLocked=D.uh;D.setLockedMouse=D.bf;D.setLockedKeyboard=D.af;D.getLockedKeyboard=D.ng;D.setLockedWheel=D.cf;D.moveTo=D.moveTo;D.moveToEx=D.Tg;D.moveToDefaultView=D.Re;D.moveToDefaultViewEx=D.Sg;
D.playSound=D.pc;D.playPauseSound=D.Te;D.playStopSound=D.Ue;D.pauseSound=D.kd;D.activateSound=D.Df;D.soundGetTime=D.Nh;D.soundSetTime=D.Ph;D.soundSetPlaybackRate=D.Oh;D.setMediaVisibility=D.wh;D.isPlaying=D.Ng;D.stopSound=D.sd;D.setVolume=D.Fh;D.changeVolume=D.Pf;D.mute=D.Xg;D.unmute=D.ei;D.toggleMuted=D.Xh;D.getHasSounds=D.dg;D.getSoundsPermitted=D.Cg;D.startAutoplayMedia=D.Rh;D.removeHotspots=D.hh;D.getHotspotsVisible=D.fg;D.getHotspotPropValue=D.ne;D.setHotspotPropValue=D.Ze;
D.getCustomPropertyDefaultValue=D.cg;D.addHotspot=D.Ef;D.updateHotspot=D.gi;D.removeHotspot=D.gh;D.getPointHotspotIds=D.yg;D.getHotspot=D.me;D.setFullscreen=D.ab;D.toggleFullscreen=D.wc;D.enterFullscreen=D.Vf;D.exitFullscreen=D.exitFullscreen;D.getIsFullscreen=D.oe;D.startAutorotate=D.hf;D.stopAutorotate=D.kf;D.toggleAutorotate=D.rf;D.pauseAutorotate=D.ah;D.resumeAutorotate=D.jh;D.setAutorotateNodeFilter=D.mh;D.createLayers=D.Jc;D.getScreenResolution=D.re;D.getMaxScreenResolution=D.og;
D.getCurrentPointHotspots=D.bg;D.setElementIdPrefix=D.qh;D.getMediaObject=D.pe;D.getMediaBufferSourceObject=D.pg;D.registerVideoElement=D.fh;D.disableSoundLoading=D.ce;D.setCrossOrigin=D.ph;D.addVariable=D.Gf;D.setVariableOptions=D.ef;D.setVariableValue=D.sc;D.getVariableValue=D.Gg;D.setSuperCookie=D.Dh;D.getOS=D.tg;D.getBrowser=D.$f;D.getBrowserTheme=D.ag;D.triggerEvent=D.o;D.requestRedraw=D.ih;D.getHasTouch=D.le;D.updateViewerSizeNow=D.Ad;D.getApiVersion=D.Zf;D.setApiVersion=D.lh;
D.getZoomCenterCursor=D.Ig;D.setZoomCenterCursor=D.Ih;D.getPlayerState=D.qe;D.setPlayerState=D.df;D.getQueryParameter=D.getQueryParameter;D.setQueryParameter=D.zh;D.getNodeUserdata=D.sg;D.setActiveHotspot=D.Pb;
